// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(taroturn_coreFFI)
    import taroturn_coreFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_taroturn_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_taroturn_core_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt16: FfiConverterPrimitive {
    typealias FfiType = Int16
    typealias SwiftType = Int16

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int16 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Int16, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public struct Card {
    public var id: UInt8
    public var key: String
    public var arcana: ArcanaType
    public var suit: Suit?
    public var rank: Rank?
    public var element: Element
    public var nameEn: String
    public var nameZh: String
    public var astrology: String?
    public var hebrewLetter: String?
    public var facets: CardFacets

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(id: UInt8, key: String, arcana: ArcanaType, suit: Suit?, rank: Rank?, element: Element, nameEn: String, nameZh: String, astrology: String?, hebrewLetter: String?, facets: CardFacets) {
        self.id = id
        self.key = key
        self.arcana = arcana
        self.suit = suit
        self.rank = rank
        self.element = element
        self.nameEn = nameEn
        self.nameZh = nameZh
        self.astrology = astrology
        self.hebrewLetter = hebrewLetter
        self.facets = facets
    }
}

extension Card: Equatable, Hashable {
    public static func == (lhs: Card, rhs: Card) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.key != rhs.key {
            return false
        }
        if lhs.arcana != rhs.arcana {
            return false
        }
        if lhs.suit != rhs.suit {
            return false
        }
        if lhs.rank != rhs.rank {
            return false
        }
        if lhs.element != rhs.element {
            return false
        }
        if lhs.nameEn != rhs.nameEn {
            return false
        }
        if lhs.nameZh != rhs.nameZh {
            return false
        }
        if lhs.astrology != rhs.astrology {
            return false
        }
        if lhs.hebrewLetter != rhs.hebrewLetter {
            return false
        }
        if lhs.facets != rhs.facets {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(key)
        hasher.combine(arcana)
        hasher.combine(suit)
        hasher.combine(rank)
        hasher.combine(element)
        hasher.combine(nameEn)
        hasher.combine(nameZh)
        hasher.combine(astrology)
        hasher.combine(hebrewLetter)
        hasher.combine(facets)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Card {
        return
            try Card(
                id: FfiConverterUInt8.read(from: &buf),
                key: FfiConverterString.read(from: &buf),
                arcana: FfiConverterTypeArcanaType.read(from: &buf),
                suit: FfiConverterOptionTypeSuit.read(from: &buf),
                rank: FfiConverterOptionTypeRank.read(from: &buf),
                element: FfiConverterTypeElement.read(from: &buf),
                nameEn: FfiConverterString.read(from: &buf),
                nameZh: FfiConverterString.read(from: &buf),
                astrology: FfiConverterOptionString.read(from: &buf),
                hebrewLetter: FfiConverterOptionString.read(from: &buf),
                facets: FfiConverterTypeCardFacets.read(from: &buf)
            )
    }

    public static func write(_ value: Card, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.id, into: &buf)
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterTypeArcanaType.write(value.arcana, into: &buf)
        FfiConverterOptionTypeSuit.write(value.suit, into: &buf)
        FfiConverterOptionTypeRank.write(value.rank, into: &buf)
        FfiConverterTypeElement.write(value.element, into: &buf)
        FfiConverterString.write(value.nameEn, into: &buf)
        FfiConverterString.write(value.nameZh, into: &buf)
        FfiConverterOptionString.write(value.astrology, into: &buf)
        FfiConverterOptionString.write(value.hebrewLetter, into: &buf)
        FfiConverterTypeCardFacets.write(value.facets, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCard_lift(_ buf: RustBuffer) throws -> Card {
    return try FfiConverterTypeCard.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCard_lower(_ value: Card) -> RustBuffer {
    return FfiConverterTypeCard.lower(value)
}

public struct CardFacets {
    public var generalUpright: [String]
    public var generalReversed: [String]
    public var loveUpright: String
    public var loveReversed: String
    public var careerUpright: String
    public var careerReversed: String
    public var spiritualUpright: String
    public var spiritualReversed: String
    public var shadowAspect: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(generalUpright: [String], generalReversed: [String], loveUpright: String, loveReversed: String, careerUpright: String, careerReversed: String, spiritualUpright: String, spiritualReversed: String, shadowAspect: String) {
        self.generalUpright = generalUpright
        self.generalReversed = generalReversed
        self.loveUpright = loveUpright
        self.loveReversed = loveReversed
        self.careerUpright = careerUpright
        self.careerReversed = careerReversed
        self.spiritualUpright = spiritualUpright
        self.spiritualReversed = spiritualReversed
        self.shadowAspect = shadowAspect
    }
}

extension CardFacets: Equatable, Hashable {
    public static func == (lhs: CardFacets, rhs: CardFacets) -> Bool {
        if lhs.generalUpright != rhs.generalUpright {
            return false
        }
        if lhs.generalReversed != rhs.generalReversed {
            return false
        }
        if lhs.loveUpright != rhs.loveUpright {
            return false
        }
        if lhs.loveReversed != rhs.loveReversed {
            return false
        }
        if lhs.careerUpright != rhs.careerUpright {
            return false
        }
        if lhs.careerReversed != rhs.careerReversed {
            return false
        }
        if lhs.spiritualUpright != rhs.spiritualUpright {
            return false
        }
        if lhs.spiritualReversed != rhs.spiritualReversed {
            return false
        }
        if lhs.shadowAspect != rhs.shadowAspect {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(generalUpright)
        hasher.combine(generalReversed)
        hasher.combine(loveUpright)
        hasher.combine(loveReversed)
        hasher.combine(careerUpright)
        hasher.combine(careerReversed)
        hasher.combine(spiritualUpright)
        hasher.combine(spiritualReversed)
        hasher.combine(shadowAspect)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCardFacets: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CardFacets {
        return
            try CardFacets(
                generalUpright: FfiConverterSequenceString.read(from: &buf),
                generalReversed: FfiConverterSequenceString.read(from: &buf),
                loveUpright: FfiConverterString.read(from: &buf),
                loveReversed: FfiConverterString.read(from: &buf),
                careerUpright: FfiConverterString.read(from: &buf),
                careerReversed: FfiConverterString.read(from: &buf),
                spiritualUpright: FfiConverterString.read(from: &buf),
                spiritualReversed: FfiConverterString.read(from: &buf),
                shadowAspect: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: CardFacets, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.generalUpright, into: &buf)
        FfiConverterSequenceString.write(value.generalReversed, into: &buf)
        FfiConverterString.write(value.loveUpright, into: &buf)
        FfiConverterString.write(value.loveReversed, into: &buf)
        FfiConverterString.write(value.careerUpright, into: &buf)
        FfiConverterString.write(value.careerReversed, into: &buf)
        FfiConverterString.write(value.spiritualUpright, into: &buf)
        FfiConverterString.write(value.spiritualReversed, into: &buf)
        FfiConverterString.write(value.shadowAspect, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCardFacets_lift(_ buf: RustBuffer) throws -> CardFacets {
    return try FfiConverterTypeCardFacets.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCardFacets_lower(_ value: CardFacets) -> RustBuffer {
    return FfiConverterTypeCardFacets.lower(value)
}

public struct DrawnCard {
    public var cardId: UInt8
    public var orientation: Orientation
    public var drawSequence: UInt8

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(cardId: UInt8, orientation: Orientation, drawSequence: UInt8) {
        self.cardId = cardId
        self.orientation = orientation
        self.drawSequence = drawSequence
    }
}

extension DrawnCard: Equatable, Hashable {
    public static func == (lhs: DrawnCard, rhs: DrawnCard) -> Bool {
        if lhs.cardId != rhs.cardId {
            return false
        }
        if lhs.orientation != rhs.orientation {
            return false
        }
        if lhs.drawSequence != rhs.drawSequence {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cardId)
        hasher.combine(orientation)
        hasher.combine(drawSequence)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrawnCard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrawnCard {
        return
            try DrawnCard(
                cardId: FfiConverterUInt8.read(from: &buf),
                orientation: FfiConverterTypeOrientation.read(from: &buf),
                drawSequence: FfiConverterUInt8.read(from: &buf)
            )
    }

    public static func write(_ value: DrawnCard, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.cardId, into: &buf)
        FfiConverterTypeOrientation.write(value.orientation, into: &buf)
        FfiConverterUInt8.write(value.drawSequence, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDrawnCard_lift(_ buf: RustBuffer) throws -> DrawnCard {
    return try FfiConverterTypeDrawnCard.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDrawnCard_lower(_ value: DrawnCard) -> RustBuffer {
    return FfiConverterTypeDrawnCard.lower(value)
}

public struct ElementalDignitySummary {
    public var fireRatio: Float
    public var waterRatio: Float
    public var airRatio: Float
    public var earthRatio: Float
    public var majorRatio: Float
    public var reversedRatio: Float
    public var dominantElement: DominantElement
    public var shadowCardId: UInt8?
    public var pairwiseDignities: [PairwiseDignity]
    public var overallHarmonyScore: Float
    public var balanceDescriptionZh: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(fireRatio: Float, waterRatio: Float, airRatio: Float, earthRatio: Float, majorRatio: Float, reversedRatio: Float, dominantElement: DominantElement, shadowCardId: UInt8?, pairwiseDignities: [PairwiseDignity], overallHarmonyScore: Float, balanceDescriptionZh: String) {
        self.fireRatio = fireRatio
        self.waterRatio = waterRatio
        self.airRatio = airRatio
        self.earthRatio = earthRatio
        self.majorRatio = majorRatio
        self.reversedRatio = reversedRatio
        self.dominantElement = dominantElement
        self.shadowCardId = shadowCardId
        self.pairwiseDignities = pairwiseDignities
        self.overallHarmonyScore = overallHarmonyScore
        self.balanceDescriptionZh = balanceDescriptionZh
    }
}

extension ElementalDignitySummary: Equatable, Hashable {
    public static func == (lhs: ElementalDignitySummary, rhs: ElementalDignitySummary) -> Bool {
        if lhs.fireRatio != rhs.fireRatio {
            return false
        }
        if lhs.waterRatio != rhs.waterRatio {
            return false
        }
        if lhs.airRatio != rhs.airRatio {
            return false
        }
        if lhs.earthRatio != rhs.earthRatio {
            return false
        }
        if lhs.majorRatio != rhs.majorRatio {
            return false
        }
        if lhs.reversedRatio != rhs.reversedRatio {
            return false
        }
        if lhs.dominantElement != rhs.dominantElement {
            return false
        }
        if lhs.shadowCardId != rhs.shadowCardId {
            return false
        }
        if lhs.pairwiseDignities != rhs.pairwiseDignities {
            return false
        }
        if lhs.overallHarmonyScore != rhs.overallHarmonyScore {
            return false
        }
        if lhs.balanceDescriptionZh != rhs.balanceDescriptionZh {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fireRatio)
        hasher.combine(waterRatio)
        hasher.combine(airRatio)
        hasher.combine(earthRatio)
        hasher.combine(majorRatio)
        hasher.combine(reversedRatio)
        hasher.combine(dominantElement)
        hasher.combine(shadowCardId)
        hasher.combine(pairwiseDignities)
        hasher.combine(overallHarmonyScore)
        hasher.combine(balanceDescriptionZh)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeElementalDignitySummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ElementalDignitySummary {
        return
            try ElementalDignitySummary(
                fireRatio: FfiConverterFloat.read(from: &buf),
                waterRatio: FfiConverterFloat.read(from: &buf),
                airRatio: FfiConverterFloat.read(from: &buf),
                earthRatio: FfiConverterFloat.read(from: &buf),
                majorRatio: FfiConverterFloat.read(from: &buf),
                reversedRatio: FfiConverterFloat.read(from: &buf),
                dominantElement: FfiConverterTypeDominantElement.read(from: &buf),
                shadowCardId: FfiConverterOptionUInt8.read(from: &buf),
                pairwiseDignities: FfiConverterSequenceTypePairwiseDignity.read(from: &buf),
                overallHarmonyScore: FfiConverterFloat.read(from: &buf),
                balanceDescriptionZh: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: ElementalDignitySummary, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.fireRatio, into: &buf)
        FfiConverterFloat.write(value.waterRatio, into: &buf)
        FfiConverterFloat.write(value.airRatio, into: &buf)
        FfiConverterFloat.write(value.earthRatio, into: &buf)
        FfiConverterFloat.write(value.majorRatio, into: &buf)
        FfiConverterFloat.write(value.reversedRatio, into: &buf)
        FfiConverterTypeDominantElement.write(value.dominantElement, into: &buf)
        FfiConverterOptionUInt8.write(value.shadowCardId, into: &buf)
        FfiConverterSequenceTypePairwiseDignity.write(value.pairwiseDignities, into: &buf)
        FfiConverterFloat.write(value.overallHarmonyScore, into: &buf)
        FfiConverterString.write(value.balanceDescriptionZh, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElementalDignitySummary_lift(_ buf: RustBuffer) throws -> ElementalDignitySummary {
    return try FfiConverterTypeElementalDignitySummary.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElementalDignitySummary_lower(_ value: ElementalDignitySummary) -> RustBuffer {
    return FfiConverterTypeElementalDignitySummary.lower(value)
}

public struct PairwiseDignity {
    public var sourceSlotId: UInt8
    public var targetSlotId: UInt8
    public var sourceCardId: UInt8
    public var targetCardId: UInt8
    public var relation: SlotRelationType
    public var sourceElement: Element
    public var targetElement: Element
    public var affinity: ElementalAffinity
    public var dignityStatus: DignityStatus
    public var tensionScore: Float
    public var dynamicSummaryZh: String

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(sourceSlotId: UInt8, targetSlotId: UInt8, sourceCardId: UInt8, targetCardId: UInt8, relation: SlotRelationType, sourceElement: Element, targetElement: Element, affinity: ElementalAffinity, dignityStatus: DignityStatus, tensionScore: Float, dynamicSummaryZh: String) {
        self.sourceSlotId = sourceSlotId
        self.targetSlotId = targetSlotId
        self.sourceCardId = sourceCardId
        self.targetCardId = targetCardId
        self.relation = relation
        self.sourceElement = sourceElement
        self.targetElement = targetElement
        self.affinity = affinity
        self.dignityStatus = dignityStatus
        self.tensionScore = tensionScore
        self.dynamicSummaryZh = dynamicSummaryZh
    }
}

extension PairwiseDignity: Equatable, Hashable {
    public static func == (lhs: PairwiseDignity, rhs: PairwiseDignity) -> Bool {
        if lhs.sourceSlotId != rhs.sourceSlotId {
            return false
        }
        if lhs.targetSlotId != rhs.targetSlotId {
            return false
        }
        if lhs.sourceCardId != rhs.sourceCardId {
            return false
        }
        if lhs.targetCardId != rhs.targetCardId {
            return false
        }
        if lhs.relation != rhs.relation {
            return false
        }
        if lhs.sourceElement != rhs.sourceElement {
            return false
        }
        if lhs.targetElement != rhs.targetElement {
            return false
        }
        if lhs.affinity != rhs.affinity {
            return false
        }
        if lhs.dignityStatus != rhs.dignityStatus {
            return false
        }
        if lhs.tensionScore != rhs.tensionScore {
            return false
        }
        if lhs.dynamicSummaryZh != rhs.dynamicSummaryZh {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sourceSlotId)
        hasher.combine(targetSlotId)
        hasher.combine(sourceCardId)
        hasher.combine(targetCardId)
        hasher.combine(relation)
        hasher.combine(sourceElement)
        hasher.combine(targetElement)
        hasher.combine(affinity)
        hasher.combine(dignityStatus)
        hasher.combine(tensionScore)
        hasher.combine(dynamicSummaryZh)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePairwiseDignity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairwiseDignity {
        return
            try PairwiseDignity(
                sourceSlotId: FfiConverterUInt8.read(from: &buf),
                targetSlotId: FfiConverterUInt8.read(from: &buf),
                sourceCardId: FfiConverterUInt8.read(from: &buf),
                targetCardId: FfiConverterUInt8.read(from: &buf),
                relation: FfiConverterTypeSlotRelationType.read(from: &buf),
                sourceElement: FfiConverterTypeElement.read(from: &buf),
                targetElement: FfiConverterTypeElement.read(from: &buf),
                affinity: FfiConverterTypeElementalAffinity.read(from: &buf),
                dignityStatus: FfiConverterTypeDignityStatus.read(from: &buf),
                tensionScore: FfiConverterFloat.read(from: &buf),
                dynamicSummaryZh: FfiConverterString.read(from: &buf)
            )
    }

    public static func write(_ value: PairwiseDignity, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.sourceSlotId, into: &buf)
        FfiConverterUInt8.write(value.targetSlotId, into: &buf)
        FfiConverterUInt8.write(value.sourceCardId, into: &buf)
        FfiConverterUInt8.write(value.targetCardId, into: &buf)
        FfiConverterTypeSlotRelationType.write(value.relation, into: &buf)
        FfiConverterTypeElement.write(value.sourceElement, into: &buf)
        FfiConverterTypeElement.write(value.targetElement, into: &buf)
        FfiConverterTypeElementalAffinity.write(value.affinity, into: &buf)
        FfiConverterTypeDignityStatus.write(value.dignityStatus, into: &buf)
        FfiConverterFloat.write(value.tensionScore, into: &buf)
        FfiConverterString.write(value.dynamicSummaryZh, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseDignity_lift(_ buf: RustBuffer) throws -> PairwiseDignity {
    return try FfiConverterTypePairwiseDignity.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePairwiseDignity_lower(_ value: PairwiseDignity) -> RustBuffer {
    return FfiConverterTypePairwiseDignity.lower(value)
}

public struct PlacedCard {
    public var slotId: UInt8
    public var drawnCard: DrawnCard

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(slotId: UInt8, drawnCard: DrawnCard) {
        self.slotId = slotId
        self.drawnCard = drawnCard
    }
}

extension PlacedCard: Equatable, Hashable {
    public static func == (lhs: PlacedCard, rhs: PlacedCard) -> Bool {
        if lhs.slotId != rhs.slotId {
            return false
        }
        if lhs.drawnCard != rhs.drawnCard {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(slotId)
        hasher.combine(drawnCard)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePlacedCard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlacedCard {
        return
            try PlacedCard(
                slotId: FfiConverterUInt8.read(from: &buf),
                drawnCard: FfiConverterTypeDrawnCard.read(from: &buf)
            )
    }

    public static func write(_ value: PlacedCard, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.slotId, into: &buf)
        FfiConverterTypeDrawnCard.write(value.drawnCard, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePlacedCard_lift(_ buf: RustBuffer) throws -> PlacedCard {
    return try FfiConverterTypePlacedCard.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePlacedCard_lower(_ value: PlacedCard) -> RustBuffer {
    return FfiConverterTypePlacedCard.lower(value)
}

public struct ReadingSession {
    public var sessionId: String
    public var createdAt: Int64
    public var spreadId: String
    public var question: String?
    public var rngSeed: String
    public var reversalProbability: Float
    public var placedCards: [PlacedCard]
    public var dignitySummary: ElementalDignitySummary
    public var userNotes: String?
    public var tags: [String]
    public var aiInterpretation: String?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(sessionId: String, createdAt: Int64, spreadId: String, question: String?, rngSeed: String, reversalProbability: Float, placedCards: [PlacedCard], dignitySummary: ElementalDignitySummary, userNotes: String?, tags: [String], aiInterpretation: String?) {
        self.sessionId = sessionId
        self.createdAt = createdAt
        self.spreadId = spreadId
        self.question = question
        self.rngSeed = rngSeed
        self.reversalProbability = reversalProbability
        self.placedCards = placedCards
        self.dignitySummary = dignitySummary
        self.userNotes = userNotes
        self.tags = tags
        self.aiInterpretation = aiInterpretation
    }
}

extension ReadingSession: Equatable, Hashable {
    public static func == (lhs: ReadingSession, rhs: ReadingSession) -> Bool {
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.spreadId != rhs.spreadId {
            return false
        }
        if lhs.question != rhs.question {
            return false
        }
        if lhs.rngSeed != rhs.rngSeed {
            return false
        }
        if lhs.reversalProbability != rhs.reversalProbability {
            return false
        }
        if lhs.placedCards != rhs.placedCards {
            return false
        }
        if lhs.dignitySummary != rhs.dignitySummary {
            return false
        }
        if lhs.userNotes != rhs.userNotes {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.aiInterpretation != rhs.aiInterpretation {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sessionId)
        hasher.combine(createdAt)
        hasher.combine(spreadId)
        hasher.combine(question)
        hasher.combine(rngSeed)
        hasher.combine(reversalProbability)
        hasher.combine(placedCards)
        hasher.combine(dignitySummary)
        hasher.combine(userNotes)
        hasher.combine(tags)
        hasher.combine(aiInterpretation)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeReadingSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReadingSession {
        return
            try ReadingSession(
                sessionId: FfiConverterString.read(from: &buf),
                createdAt: FfiConverterInt64.read(from: &buf),
                spreadId: FfiConverterString.read(from: &buf),
                question: FfiConverterOptionString.read(from: &buf),
                rngSeed: FfiConverterString.read(from: &buf),
                reversalProbability: FfiConverterFloat.read(from: &buf),
                placedCards: FfiConverterSequenceTypePlacedCard.read(from: &buf),
                dignitySummary: FfiConverterTypeElementalDignitySummary.read(from: &buf),
                userNotes: FfiConverterOptionString.read(from: &buf),
                tags: FfiConverterSequenceString.read(from: &buf),
                aiInterpretation: FfiConverterOptionString.read(from: &buf)
            )
    }

    public static func write(_ value: ReadingSession, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterInt64.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.spreadId, into: &buf)
        FfiConverterOptionString.write(value.question, into: &buf)
        FfiConverterString.write(value.rngSeed, into: &buf)
        FfiConverterFloat.write(value.reversalProbability, into: &buf)
        FfiConverterSequenceTypePlacedCard.write(value.placedCards, into: &buf)
        FfiConverterTypeElementalDignitySummary.write(value.dignitySummary, into: &buf)
        FfiConverterOptionString.write(value.userNotes, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionString.write(value.aiInterpretation, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeReadingSession_lift(_ buf: RustBuffer) throws -> ReadingSession {
    return try FfiConverterTypeReadingSession.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeReadingSession_lower(_ value: ReadingSession) -> RustBuffer {
    return FfiConverterTypeReadingSession.lower(value)
}

public struct SlotEdge {
    public var sourceSlotId: UInt8
    public var targetSlotId: UInt8
    public var relation: SlotRelationType
    public var weight: Float

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(sourceSlotId: UInt8, targetSlotId: UInt8, relation: SlotRelationType, weight: Float) {
        self.sourceSlotId = sourceSlotId
        self.targetSlotId = targetSlotId
        self.relation = relation
        self.weight = weight
    }
}

extension SlotEdge: Equatable, Hashable {
    public static func == (lhs: SlotEdge, rhs: SlotEdge) -> Bool {
        if lhs.sourceSlotId != rhs.sourceSlotId {
            return false
        }
        if lhs.targetSlotId != rhs.targetSlotId {
            return false
        }
        if lhs.relation != rhs.relation {
            return false
        }
        if lhs.weight != rhs.weight {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sourceSlotId)
        hasher.combine(targetSlotId)
        hasher.combine(relation)
        hasher.combine(weight)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSlotEdge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SlotEdge {
        return
            try SlotEdge(
                sourceSlotId: FfiConverterUInt8.read(from: &buf),
                targetSlotId: FfiConverterUInt8.read(from: &buf),
                relation: FfiConverterTypeSlotRelationType.read(from: &buf),
                weight: FfiConverterFloat.read(from: &buf)
            )
    }

    public static func write(_ value: SlotEdge, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.sourceSlotId, into: &buf)
        FfiConverterUInt8.write(value.targetSlotId, into: &buf)
        FfiConverterTypeSlotRelationType.write(value.relation, into: &buf)
        FfiConverterFloat.write(value.weight, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotEdge_lift(_ buf: RustBuffer) throws -> SlotEdge {
    return try FfiConverterTypeSlotEdge.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotEdge_lower(_ value: SlotEdge) -> RustBuffer {
    return FfiConverterTypeSlotEdge.lower(value)
}

public struct Spread {
    public var id: String
    public var nameEn: String
    public var nameZh: String
    public var description: String
    public var category: SpreadCategory
    public var slots: [SpreadSlot]
    public var edges: [SlotEdge]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(id: String, nameEn: String, nameZh: String, description: String, category: SpreadCategory, slots: [SpreadSlot], edges: [SlotEdge]) {
        self.id = id
        self.nameEn = nameEn
        self.nameZh = nameZh
        self.description = description
        self.category = category
        self.slots = slots
        self.edges = edges
    }
}

extension Spread: Equatable, Hashable {
    public static func == (lhs: Spread, rhs: Spread) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.nameEn != rhs.nameEn {
            return false
        }
        if lhs.nameZh != rhs.nameZh {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.category != rhs.category {
            return false
        }
        if lhs.slots != rhs.slots {
            return false
        }
        if lhs.edges != rhs.edges {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(nameEn)
        hasher.combine(nameZh)
        hasher.combine(description)
        hasher.combine(category)
        hasher.combine(slots)
        hasher.combine(edges)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpread: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Spread {
        return
            try Spread(
                id: FfiConverterString.read(from: &buf),
                nameEn: FfiConverterString.read(from: &buf),
                nameZh: FfiConverterString.read(from: &buf),
                description: FfiConverterString.read(from: &buf),
                category: FfiConverterTypeSpreadCategory.read(from: &buf),
                slots: FfiConverterSequenceTypeSpreadSlot.read(from: &buf),
                edges: FfiConverterSequenceTypeSlotEdge.read(from: &buf)
            )
    }

    public static func write(_ value: Spread, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.nameEn, into: &buf)
        FfiConverterString.write(value.nameZh, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterTypeSpreadCategory.write(value.category, into: &buf)
        FfiConverterSequenceTypeSpreadSlot.write(value.slots, into: &buf)
        FfiConverterSequenceTypeSlotEdge.write(value.edges, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpread_lift(_ buf: RustBuffer) throws -> Spread {
    return try FfiConverterTypeSpread.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpread_lower(_ value: Spread) -> RustBuffer {
    return FfiConverterTypeSpread.lower(value)
}

public struct SpreadSlot {
    public var slotId: UInt8
    public var titleEn: String
    public var titleZh: String
    public var meaningPrompt: String
    public var x: Float
    public var y: Float
    public var rotationDeg: Float
    public var zIndex: Int16
    public var constraint: SlotConstraint

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(slotId: UInt8, titleEn: String, titleZh: String, meaningPrompt: String, x: Float, y: Float, rotationDeg: Float, zIndex: Int16, constraint: SlotConstraint) {
        self.slotId = slotId
        self.titleEn = titleEn
        self.titleZh = titleZh
        self.meaningPrompt = meaningPrompt
        self.x = x
        self.y = y
        self.rotationDeg = rotationDeg
        self.zIndex = zIndex
        self.constraint = constraint
    }
}

extension SpreadSlot: Equatable, Hashable {
    public static func == (lhs: SpreadSlot, rhs: SpreadSlot) -> Bool {
        if lhs.slotId != rhs.slotId {
            return false
        }
        if lhs.titleEn != rhs.titleEn {
            return false
        }
        if lhs.titleZh != rhs.titleZh {
            return false
        }
        if lhs.meaningPrompt != rhs.meaningPrompt {
            return false
        }
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.rotationDeg != rhs.rotationDeg {
            return false
        }
        if lhs.zIndex != rhs.zIndex {
            return false
        }
        if lhs.constraint != rhs.constraint {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(slotId)
        hasher.combine(titleEn)
        hasher.combine(titleZh)
        hasher.combine(meaningPrompt)
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(rotationDeg)
        hasher.combine(zIndex)
        hasher.combine(constraint)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpreadSlot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpreadSlot {
        return
            try SpreadSlot(
                slotId: FfiConverterUInt8.read(from: &buf),
                titleEn: FfiConverterString.read(from: &buf),
                titleZh: FfiConverterString.read(from: &buf),
                meaningPrompt: FfiConverterString.read(from: &buf),
                x: FfiConverterFloat.read(from: &buf),
                y: FfiConverterFloat.read(from: &buf),
                rotationDeg: FfiConverterFloat.read(from: &buf),
                zIndex: FfiConverterInt16.read(from: &buf),
                constraint: FfiConverterTypeSlotConstraint.read(from: &buf)
            )
    }

    public static func write(_ value: SpreadSlot, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.slotId, into: &buf)
        FfiConverterString.write(value.titleEn, into: &buf)
        FfiConverterString.write(value.titleZh, into: &buf)
        FfiConverterString.write(value.meaningPrompt, into: &buf)
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterFloat.write(value.rotationDeg, into: &buf)
        FfiConverterInt16.write(value.zIndex, into: &buf)
        FfiConverterTypeSlotConstraint.write(value.constraint, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpreadSlot_lift(_ buf: RustBuffer) throws -> SpreadSlot {
    return try FfiConverterTypeSpreadSlot.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpreadSlot_lower(_ value: SpreadSlot) -> RustBuffer {
    return FfiConverterTypeSpreadSlot.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ArcanaType {
    case major
    case minor
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeArcanaType: FfiConverterRustBuffer {
    typealias SwiftType = ArcanaType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ArcanaType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .major

        case 2: return .minor

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ArcanaType, into buf: inout [UInt8]) {
        switch value {
        case .major:
            writeInt(&buf, Int32(1))

        case .minor:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeArcanaType_lift(_ buf: RustBuffer) throws -> ArcanaType {
    return try FfiConverterTypeArcanaType.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeArcanaType_lower(_ value: ArcanaType) -> RustBuffer {
    return FfiConverterTypeArcanaType.lower(value)
}

extension ArcanaType: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DignityStatus {
    case wellDignified
    case illDignified
    case neutralDignified
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDignityStatus: FfiConverterRustBuffer {
    typealias SwiftType = DignityStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DignityStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .wellDignified

        case 2: return .illDignified

        case 3: return .neutralDignified

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DignityStatus, into buf: inout [UInt8]) {
        switch value {
        case .wellDignified:
            writeInt(&buf, Int32(1))

        case .illDignified:
            writeInt(&buf, Int32(2))

        case .neutralDignified:
            writeInt(&buf, Int32(3))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDignityStatus_lift(_ buf: RustBuffer) throws -> DignityStatus {
    return try FfiConverterTypeDignityStatus.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDignityStatus_lower(_ value: DignityStatus) -> RustBuffer {
    return FfiConverterTypeDignityStatus.lower(value)
}

extension DignityStatus: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DominantElement {
    case fire
    case water
    case air
    case earth
    case balanced
    case none
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDominantElement: FfiConverterRustBuffer {
    typealias SwiftType = DominantElement

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DominantElement {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .fire

        case 2: return .water

        case 3: return .air

        case 4: return .earth

        case 5: return .balanced

        case 6: return .none

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DominantElement, into buf: inout [UInt8]) {
        switch value {
        case .fire:
            writeInt(&buf, Int32(1))

        case .water:
            writeInt(&buf, Int32(2))

        case .air:
            writeInt(&buf, Int32(3))

        case .earth:
            writeInt(&buf, Int32(4))

        case .balanced:
            writeInt(&buf, Int32(5))

        case .none:
            writeInt(&buf, Int32(6))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDominantElement_lift(_ buf: RustBuffer) throws -> DominantElement {
    return try FfiConverterTypeDominantElement.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDominantElement_lower(_ value: DominantElement) -> RustBuffer {
    return FfiConverterTypeDominantElement.lower(value)
}

extension DominantElement: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Element {
    case fire
    case water
    case air
    case earth
    case spirit
    case none
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeElement: FfiConverterRustBuffer {
    typealias SwiftType = Element

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Element {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .fire

        case 2: return .water

        case 3: return .air

        case 4: return .earth

        case 5: return .spirit

        case 6: return .none

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Element, into buf: inout [UInt8]) {
        switch value {
        case .fire:
            writeInt(&buf, Int32(1))

        case .water:
            writeInt(&buf, Int32(2))

        case .air:
            writeInt(&buf, Int32(3))

        case .earth:
            writeInt(&buf, Int32(4))

        case .spirit:
            writeInt(&buf, Int32(5))

        case .none:
            writeInt(&buf, Int32(6))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElement_lift(_ buf: RustBuffer) throws -> Element {
    return try FfiConverterTypeElement.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElement_lower(_ value: Element) -> RustBuffer {
    return FfiConverterTypeElement.lower(value)
}

extension Element: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ElementalAffinity {
    case friendlyActive
    case friendlyPassive
    case intensified
    case contradictoryHostile
    case neutralModifying
    case undefined
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeElementalAffinity: FfiConverterRustBuffer {
    typealias SwiftType = ElementalAffinity

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ElementalAffinity {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .friendlyActive

        case 2: return .friendlyPassive

        case 3: return .intensified

        case 4: return .contradictoryHostile

        case 5: return .neutralModifying

        case 6: return .undefined

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ElementalAffinity, into buf: inout [UInt8]) {
        switch value {
        case .friendlyActive:
            writeInt(&buf, Int32(1))

        case .friendlyPassive:
            writeInt(&buf, Int32(2))

        case .intensified:
            writeInt(&buf, Int32(3))

        case .contradictoryHostile:
            writeInt(&buf, Int32(4))

        case .neutralModifying:
            writeInt(&buf, Int32(5))

        case .undefined:
            writeInt(&buf, Int32(6))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElementalAffinity_lift(_ buf: RustBuffer) throws -> ElementalAffinity {
    return try FfiConverterTypeElementalAffinity.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeElementalAffinity_lower(_ value: ElementalAffinity) -> RustBuffer {
    return FfiConverterTypeElementalAffinity.lower(value)
}

extension ElementalAffinity: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Orientation {
    case upright
    case reversed
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeOrientation: FfiConverterRustBuffer {
    typealias SwiftType = Orientation

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Orientation {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .upright

        case 2: return .reversed

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Orientation, into buf: inout [UInt8]) {
        switch value {
        case .upright:
            writeInt(&buf, Int32(1))

        case .reversed:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeOrientation_lift(_ buf: RustBuffer) throws -> Orientation {
    return try FfiConverterTypeOrientation.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeOrientation_lower(_ value: Orientation) -> RustBuffer {
    return FfiConverterTypeOrientation.lower(value)
}

extension Orientation: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Rank {
    case ace
    case two
    case three
    case four
    case five
    case six
    case seven
    case eight
    case nine
    case ten
    case page
    case knight
    case queen
    case king
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeRank: FfiConverterRustBuffer {
    typealias SwiftType = Rank

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Rank {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .ace

        case 2: return .two

        case 3: return .three

        case 4: return .four

        case 5: return .five

        case 6: return .six

        case 7: return .seven

        case 8: return .eight

        case 9: return .nine

        case 10: return .ten

        case 11: return .page

        case 12: return .knight

        case 13: return .queen

        case 14: return .king

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Rank, into buf: inout [UInt8]) {
        switch value {
        case .ace:
            writeInt(&buf, Int32(1))

        case .two:
            writeInt(&buf, Int32(2))

        case .three:
            writeInt(&buf, Int32(3))

        case .four:
            writeInt(&buf, Int32(4))

        case .five:
            writeInt(&buf, Int32(5))

        case .six:
            writeInt(&buf, Int32(6))

        case .seven:
            writeInt(&buf, Int32(7))

        case .eight:
            writeInt(&buf, Int32(8))

        case .nine:
            writeInt(&buf, Int32(9))

        case .ten:
            writeInt(&buf, Int32(10))

        case .page:
            writeInt(&buf, Int32(11))

        case .knight:
            writeInt(&buf, Int32(12))

        case .queen:
            writeInt(&buf, Int32(13))

        case .king:
            writeInt(&buf, Int32(14))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeRank_lift(_ buf: RustBuffer) throws -> Rank {
    return try FfiConverterTypeRank.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeRank_lower(_ value: Rank) -> RustBuffer {
    return FfiConverterTypeRank.lower(value)
}

extension Rank: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SlotConstraint {
    case any
    case majorOnly
    case minorOnly
    case wandsOnly
    case cupsOnly
    case swordsOnly
    case pentaclesOnly
    case courtOnly
    case pipOnly
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSlotConstraint: FfiConverterRustBuffer {
    typealias SwiftType = SlotConstraint

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SlotConstraint {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .any

        case 2: return .majorOnly

        case 3: return .minorOnly

        case 4: return .wandsOnly

        case 5: return .cupsOnly

        case 6: return .swordsOnly

        case 7: return .pentaclesOnly

        case 8: return .courtOnly

        case 9: return .pipOnly

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SlotConstraint, into buf: inout [UInt8]) {
        switch value {
        case .any:
            writeInt(&buf, Int32(1))

        case .majorOnly:
            writeInt(&buf, Int32(2))

        case .minorOnly:
            writeInt(&buf, Int32(3))

        case .wandsOnly:
            writeInt(&buf, Int32(4))

        case .cupsOnly:
            writeInt(&buf, Int32(5))

        case .swordsOnly:
            writeInt(&buf, Int32(6))

        case .pentaclesOnly:
            writeInt(&buf, Int32(7))

        case .courtOnly:
            writeInt(&buf, Int32(8))

        case .pipOnly:
            writeInt(&buf, Int32(9))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotConstraint_lift(_ buf: RustBuffer) throws -> SlotConstraint {
    return try FfiConverterTypeSlotConstraint.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotConstraint_lower(_ value: SlotConstraint) -> RustBuffer {
    return FfiConverterTypeSlotConstraint.lower(value)
}

extension SlotConstraint: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SlotRelationType {
    case crosses
    case flowsTo
    case supports
    case illuminates
    case opposes
    case synthesizes
    case reflects
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSlotRelationType: FfiConverterRustBuffer {
    typealias SwiftType = SlotRelationType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SlotRelationType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .crosses

        case 2: return .flowsTo

        case 3: return .supports

        case 4: return .illuminates

        case 5: return .opposes

        case 6: return .synthesizes

        case 7: return .reflects

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SlotRelationType, into buf: inout [UInt8]) {
        switch value {
        case .crosses:
            writeInt(&buf, Int32(1))

        case .flowsTo:
            writeInt(&buf, Int32(2))

        case .supports:
            writeInt(&buf, Int32(3))

        case .illuminates:
            writeInt(&buf, Int32(4))

        case .opposes:
            writeInt(&buf, Int32(5))

        case .synthesizes:
            writeInt(&buf, Int32(6))

        case .reflects:
            writeInt(&buf, Int32(7))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotRelationType_lift(_ buf: RustBuffer) throws -> SlotRelationType {
    return try FfiConverterTypeSlotRelationType.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSlotRelationType_lower(_ value: SlotRelationType) -> RustBuffer {
    return FfiConverterTypeSlotRelationType.lower(value)
}

extension SlotRelationType: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SpreadCategory {
    case daily
    case decision
    case relationship
    case comprehensive
    case custom
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpreadCategory: FfiConverterRustBuffer {
    typealias SwiftType = SpreadCategory

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SpreadCategory {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .daily

        case 2: return .decision

        case 3: return .relationship

        case 4: return .comprehensive

        case 5: return .custom

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SpreadCategory, into buf: inout [UInt8]) {
        switch value {
        case .daily:
            writeInt(&buf, Int32(1))

        case .decision:
            writeInt(&buf, Int32(2))

        case .relationship:
            writeInt(&buf, Int32(3))

        case .comprehensive:
            writeInt(&buf, Int32(4))

        case .custom:
            writeInt(&buf, Int32(5))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpreadCategory_lift(_ buf: RustBuffer) throws -> SpreadCategory {
    return try FfiConverterTypeSpreadCategory.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSpreadCategory_lower(_ value: SpreadCategory) -> RustBuffer {
    return FfiConverterTypeSpreadCategory.lower(value)
}

extension SpreadCategory: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Suit {
    case wands
    case cups
    case swords
    case pentacles
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuit: FfiConverterRustBuffer {
    typealias SwiftType = Suit

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Suit {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .wands

        case 2: return .cups

        case 3: return .swords

        case 4: return .pentacles

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Suit, into buf: inout [UInt8]) {
        switch value {
        case .wands:
            writeInt(&buf, Int32(1))

        case .cups:
            writeInt(&buf, Int32(2))

        case .swords:
            writeInt(&buf, Int32(3))

        case .pentacles:
            writeInt(&buf, Int32(4))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSuit_lift(_ buf: RustBuffer) throws -> Suit {
    return try FfiConverterTypeSuit.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSuit_lower(_ value: Suit) -> RustBuffer {
    return FfiConverterTypeSuit.lower(value)
}

extension Suit: Equatable, Hashable {}

public enum TarotError {
    case InvalidSeed(String)
    case CardIndexOutOfBounds(UInt8)
    case DuplicateCardDraw(UInt8)
    case SpreadSlotOverflow(requested: UInt64, capacity: UInt64)
    case ConstraintViolation(slotId: UInt8, required: String, actual: String)
    case SpreadNotFound(String)
    case DeserializationError(String)
    case AiProviderUnavailable(String)
    case Unauthorized(String)
    case DeckNotFound(String)
    case OtpArchiveCorrupted(String)
    case OtpManifestMissing
    case OtpManifestInvalid(String)
    case OtpIncompleteDeck(UInt32)
    case InternalLockError
    case IoError(String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeTarotError: FfiConverterRustBuffer {
    typealias SwiftType = TarotError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TarotError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .InvalidSeed(
                FfiConverterString.read(from: &buf)
            )
        case 2: return try .CardIndexOutOfBounds(
                FfiConverterUInt8.read(from: &buf)
            )
        case 3: return try .DuplicateCardDraw(
                FfiConverterUInt8.read(from: &buf)
            )
        case 4: return try .SpreadSlotOverflow(
                requested: FfiConverterUInt64.read(from: &buf),
                capacity: FfiConverterUInt64.read(from: &buf)
            )
        case 5: return try .ConstraintViolation(
                slotId: FfiConverterUInt8.read(from: &buf),
                required: FfiConverterString.read(from: &buf),
                actual: FfiConverterString.read(from: &buf)
            )
        case 6: return try .SpreadNotFound(
                FfiConverterString.read(from: &buf)
            )
        case 7: return try .DeserializationError(
                FfiConverterString.read(from: &buf)
            )
        case 8: return try .AiProviderUnavailable(
                FfiConverterString.read(from: &buf)
            )
        case 9: return try .Unauthorized(
                FfiConverterString.read(from: &buf)
            )
        case 10: return try .DeckNotFound(
                FfiConverterString.read(from: &buf)
            )
        case 11: return try .OtpArchiveCorrupted(
                FfiConverterString.read(from: &buf)
            )
        case 12: return .OtpManifestMissing
        case 13: return try .OtpManifestInvalid(
                FfiConverterString.read(from: &buf)
            )
        case 14: return try .OtpIncompleteDeck(
                FfiConverterUInt32.read(from: &buf)
            )
        case 15: return .InternalLockError
        case 16: return try .IoError(
                FfiConverterString.read(from: &buf)
            )
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TarotError, into buf: inout [UInt8]) {
        switch value {
        case let .InvalidSeed(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)

        case let .CardIndexOutOfBounds(v1):
            writeInt(&buf, Int32(2))
            FfiConverterUInt8.write(v1, into: &buf)

        case let .DuplicateCardDraw(v1):
            writeInt(&buf, Int32(3))
            FfiConverterUInt8.write(v1, into: &buf)

        case let .SpreadSlotOverflow(requested, capacity):
            writeInt(&buf, Int32(4))
            FfiConverterUInt64.write(requested, into: &buf)
            FfiConverterUInt64.write(capacity, into: &buf)

        case let .ConstraintViolation(slotId, required, actual):
            writeInt(&buf, Int32(5))
            FfiConverterUInt8.write(slotId, into: &buf)
            FfiConverterString.write(required, into: &buf)
            FfiConverterString.write(actual, into: &buf)

        case let .SpreadNotFound(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)

        case let .DeserializationError(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)

        case let .AiProviderUnavailable(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)

        case let .Unauthorized(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)

        case let .DeckNotFound(v1):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(v1, into: &buf)

        case let .OtpArchiveCorrupted(v1):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(v1, into: &buf)

        case .OtpManifestMissing:
            writeInt(&buf, Int32(12))

        case let .OtpManifestInvalid(v1):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(v1, into: &buf)

        case let .OtpIncompleteDeck(v1):
            writeInt(&buf, Int32(14))
            FfiConverterUInt32.write(v1, into: &buf)

        case .InternalLockError:
            writeInt(&buf, Int32(15))

        case let .IoError(v1):
            writeInt(&buf, Int32(16))
            FfiConverterString.write(v1, into: &buf)
        }
    }
}

extension TarotError: Equatable, Hashable {}

extension TarotError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeRank: FfiConverterRustBuffer {
    typealias SwiftType = Rank?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRank.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRank.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeSuit: FfiConverterRustBuffer {
    typealias SwiftType = Suit?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSuit.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSuit.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeCard: FfiConverterRustBuffer {
    typealias SwiftType = [Card]

    static func write(_ value: [Card], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCard.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Card] {
        let len: Int32 = try readInt(&buf)
        var seq = [Card]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeCard.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypePairwiseDignity: FfiConverterRustBuffer {
    typealias SwiftType = [PairwiseDignity]

    static func write(_ value: [PairwiseDignity], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePairwiseDignity.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PairwiseDignity] {
        let len: Int32 = try readInt(&buf)
        var seq = [PairwiseDignity]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypePairwiseDignity.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypePlacedCard: FfiConverterRustBuffer {
    typealias SwiftType = [PlacedCard]

    static func write(_ value: [PlacedCard], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePlacedCard.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PlacedCard] {
        let len: Int32 = try readInt(&buf)
        var seq = [PlacedCard]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypePlacedCard.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSlotEdge: FfiConverterRustBuffer {
    typealias SwiftType = [SlotEdge]

    static func write(_ value: [SlotEdge], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSlotEdge.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SlotEdge] {
        let len: Int32 = try readInt(&buf)
        var seq = [SlotEdge]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSlotEdge.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSpread: FfiConverterRustBuffer {
    typealias SwiftType = [Spread]

    static func write(_ value: [Spread], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSpread.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Spread] {
        let len: Int32 = try readInt(&buf)
        var seq = [Spread]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSpread.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeSpreadSlot: FfiConverterRustBuffer {
    typealias SwiftType = [SpreadSlot]

    static func write(_ value: [SpreadSlot], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSpreadSlot.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SpreadSlot] {
        let len: Int32 = try readInt(&buf)
        var seq = [SpreadSlot]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSpreadSlot.read(from: &buf))
        }
        return seq
    }
}

/**
 * UniFFI Exported: Draws a deterministic reading session
 */
public func drawReadingSession(spreadId: String, question: String?, seedHex: String?, reversalRate: Float) throws -> ReadingSession {
    return try FfiConverterTypeReadingSession.lift(rustCallWithError(FfiConverterTypeTarotError.lift) {
        uniffi_taroturn_core_fn_func_draw_reading_session(
            FfiConverterString.lower(spreadId),
            FfiConverterOptionString.lower(question),
            FfiConverterOptionString.lower(seedHex),
            FfiConverterFloat.lower(reversalRate), $0
        )
    })
}

/**
 * UniFFI Exported: Generates a 64-character cryptographic CSPRNG seed
 */
public func generateRandomSeed() throws -> String {
    return try FfiConverterString.lift(rustCallWithError(FfiConverterTypeTarotError.lift) {
        uniffi_taroturn_core_fn_func_generate_random_seed($0)
    })
}

/**
 * UniFFI Exported: Retrieves a card archetype definition by card ID (0..77)
 */
public func getCardById(cardId: UInt8) throws -> Card {
    return try FfiConverterTypeCard.lift(rustCallWithError(FfiConverterTypeTarotError.lift) {
        uniffi_taroturn_core_fn_func_get_card_by_id(
            FfiConverterUInt8.lower(cardId), $0
        )
    })
}

/**
 * UniFFI Exported: Returns static library version string
 */
public func getTaroturnVersion() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_taroturn_core_fn_func_get_taroturn_version($0)
    })
}

/**
 * UniFFI Exported: Lists all 78 standard Tarot cards
 */
public func listAllCards() -> [Card] {
    return try! FfiConverterSequenceTypeCard.lift(try! rustCall {
        uniffi_taroturn_core_fn_func_list_all_cards($0)
    })
}

/**
 * UniFFI Exported: Lists all built-in canonical spreads
 */
public func listCanonicalSpreads() -> [Spread] {
    return try! FfiConverterSequenceTypeSpread.lift(try! rustCall {
        uniffi_taroturn_core_fn_func_list_canonical_spreads($0)
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_taroturn_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_taroturn_core_checksum_func_draw_reading_session() != 40058 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_taroturn_core_checksum_func_generate_random_seed() != 18692 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_taroturn_core_checksum_func_get_card_by_id() != 62755 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_taroturn_core_checksum_func_get_taroturn_version() != 63623 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_taroturn_core_checksum_func_list_all_cards() != 52176 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_taroturn_core_checksum_func_list_canonical_spreads() != 59923 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
