

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_taroturn_core_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_taroturn_core_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_taroturn_core_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("taroturn_core")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 26
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_taroturn_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_taroturn_core_checksum_func_draw_reading_session() != 40058:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_taroturn_core_checksum_func_generate_random_seed() != 18692:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_taroturn_core_checksum_func_get_card_by_id() != 62755:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_taroturn_core_checksum_func_get_taroturn_version() != 63623:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_taroturn_core_checksum_func_list_all_cards() != 52176:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_taroturn_core_checksum_func_list_canonical_spreads() != 59923:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UniffiLib.uniffi_taroturn_core_fn_func_draw_reading_session.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_float,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_draw_reading_session.restype = _UniffiRustBuffer
_UniffiLib.uniffi_taroturn_core_fn_func_generate_random_seed.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_generate_random_seed.restype = _UniffiRustBuffer
_UniffiLib.uniffi_taroturn_core_fn_func_get_card_by_id.argtypes = (
    ctypes.c_uint8,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_get_card_by_id.restype = _UniffiRustBuffer
_UniffiLib.uniffi_taroturn_core_fn_func_get_taroturn_version.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_get_taroturn_version.restype = _UniffiRustBuffer
_UniffiLib.uniffi_taroturn_core_fn_func_list_all_cards.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_list_all_cards.restype = _UniffiRustBuffer
_UniffiLib.uniffi_taroturn_core_fn_func_list_canonical_spreads.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_taroturn_core_fn_func_list_canonical_spreads.restype = _UniffiRustBuffer
_UniffiLib.ffi_taroturn_core_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_taroturn_core_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_taroturn_core_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rustbuffer_free.restype = None
_UniffiLib.ffi_taroturn_core_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_taroturn_core_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_u8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_u8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_taroturn_core_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_i8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_i8.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_taroturn_core_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_u16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_u16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_taroturn_core_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_i16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_i16.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_taroturn_core_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_u32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_u32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_taroturn_core_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_i32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_i32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_taroturn_core_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_u64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_u64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_taroturn_core_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_i64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_i64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_taroturn_core_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_f32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_f32.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_taroturn_core_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_f64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_f64.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_taroturn_core_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_pointer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_taroturn_core_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_taroturn_core_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_poll_void.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_cancel_void.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_taroturn_core_rust_future_free_void.restype = None
_UniffiLib.ffi_taroturn_core_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_taroturn_core_rust_future_complete_void.restype = None
_UniffiLib.uniffi_taroturn_core_checksum_func_draw_reading_session.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_draw_reading_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_taroturn_core_checksum_func_generate_random_seed.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_generate_random_seed.restype = ctypes.c_uint16
_UniffiLib.uniffi_taroturn_core_checksum_func_get_card_by_id.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_get_card_by_id.restype = ctypes.c_uint16
_UniffiLib.uniffi_taroturn_core_checksum_func_get_taroturn_version.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_get_taroturn_version.restype = ctypes.c_uint16
_UniffiLib.uniffi_taroturn_core_checksum_func_list_all_cards.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_list_all_cards.restype = ctypes.c_uint16
_UniffiLib.uniffi_taroturn_core_checksum_func_list_canonical_spreads.argtypes = (
)
_UniffiLib.uniffi_taroturn_core_checksum_func_list_canonical_spreads.restype = ctypes.c_uint16
_UniffiLib.ffi_taroturn_core_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_taroturn_core_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

class _UniffiConverterInt16(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i16"
    VALUE_MIN = -2**15
    VALUE_MAX = 2**15

    @staticmethod
    def read(buf):
        return buf.read_i16()

    @staticmethod
    def write(value, buf):
        buf.write_i16(value)

class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i64"
    VALUE_MIN = -2**63
    VALUE_MAX = 2**63

    @staticmethod
    def read(buf):
        return buf.read_i64()

    @staticmethod
    def write(value, buf):
        buf.write_i64(value)

class _UniffiConverterFloat(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_float()

    @staticmethod
    def write(value, buf):
        buf.write_float(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()


class Card:
    id: "int"
    key: "str"
    arcana: "ArcanaType"
    suit: "typing.Optional[Suit]"
    rank: "typing.Optional[Rank]"
    element: "Element"
    name_en: "str"
    name_zh: "str"
    astrology: "typing.Optional[str]"
    hebrew_letter: "typing.Optional[str]"
    facets: "CardFacets"
    def __init__(self, *, id: "int", key: "str", arcana: "ArcanaType", suit: "typing.Optional[Suit]", rank: "typing.Optional[Rank]", element: "Element", name_en: "str", name_zh: "str", astrology: "typing.Optional[str]", hebrew_letter: "typing.Optional[str]", facets: "CardFacets"):
        self.id = id
        self.key = key
        self.arcana = arcana
        self.suit = suit
        self.rank = rank
        self.element = element
        self.name_en = name_en
        self.name_zh = name_zh
        self.astrology = astrology
        self.hebrew_letter = hebrew_letter
        self.facets = facets

    def __str__(self):
        return "Card(id={}, key={}, arcana={}, suit={}, rank={}, element={}, name_en={}, name_zh={}, astrology={}, hebrew_letter={}, facets={})".format(self.id, self.key, self.arcana, self.suit, self.rank, self.element, self.name_en, self.name_zh, self.astrology, self.hebrew_letter, self.facets)

    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.key != other.key:
            return False
        if self.arcana != other.arcana:
            return False
        if self.suit != other.suit:
            return False
        if self.rank != other.rank:
            return False
        if self.element != other.element:
            return False
        if self.name_en != other.name_en:
            return False
        if self.name_zh != other.name_zh:
            return False
        if self.astrology != other.astrology:
            return False
        if self.hebrew_letter != other.hebrew_letter:
            return False
        if self.facets != other.facets:
            return False
        return True

class _UniffiConverterTypeCard(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Card(
            id=_UniffiConverterUInt8.read(buf),
            key=_UniffiConverterString.read(buf),
            arcana=_UniffiConverterTypeArcanaType.read(buf),
            suit=_UniffiConverterOptionalTypeSuit.read(buf),
            rank=_UniffiConverterOptionalTypeRank.read(buf),
            element=_UniffiConverterTypeElement.read(buf),
            name_en=_UniffiConverterString.read(buf),
            name_zh=_UniffiConverterString.read(buf),
            astrology=_UniffiConverterOptionalString.read(buf),
            hebrew_letter=_UniffiConverterOptionalString.read(buf),
            facets=_UniffiConverterTypeCardFacets.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt8.check_lower(value.id)
        _UniffiConverterString.check_lower(value.key)
        _UniffiConverterTypeArcanaType.check_lower(value.arcana)
        _UniffiConverterOptionalTypeSuit.check_lower(value.suit)
        _UniffiConverterOptionalTypeRank.check_lower(value.rank)
        _UniffiConverterTypeElement.check_lower(value.element)
        _UniffiConverterString.check_lower(value.name_en)
        _UniffiConverterString.check_lower(value.name_zh)
        _UniffiConverterOptionalString.check_lower(value.astrology)
        _UniffiConverterOptionalString.check_lower(value.hebrew_letter)
        _UniffiConverterTypeCardFacets.check_lower(value.facets)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt8.write(value.id, buf)
        _UniffiConverterString.write(value.key, buf)
        _UniffiConverterTypeArcanaType.write(value.arcana, buf)
        _UniffiConverterOptionalTypeSuit.write(value.suit, buf)
        _UniffiConverterOptionalTypeRank.write(value.rank, buf)
        _UniffiConverterTypeElement.write(value.element, buf)
        _UniffiConverterString.write(value.name_en, buf)
        _UniffiConverterString.write(value.name_zh, buf)
        _UniffiConverterOptionalString.write(value.astrology, buf)
        _UniffiConverterOptionalString.write(value.hebrew_letter, buf)
        _UniffiConverterTypeCardFacets.write(value.facets, buf)


class CardFacets:
    general_upright: "typing.List[str]"
    general_reversed: "typing.List[str]"
    love_upright: "str"
    love_reversed: "str"
    career_upright: "str"
    career_reversed: "str"
    spiritual_upright: "str"
    spiritual_reversed: "str"
    shadow_aspect: "str"
    def __init__(self, *, general_upright: "typing.List[str]", general_reversed: "typing.List[str]", love_upright: "str", love_reversed: "str", career_upright: "str", career_reversed: "str", spiritual_upright: "str", spiritual_reversed: "str", shadow_aspect: "str"):
        self.general_upright = general_upright
        self.general_reversed = general_reversed
        self.love_upright = love_upright
        self.love_reversed = love_reversed
        self.career_upright = career_upright
        self.career_reversed = career_reversed
        self.spiritual_upright = spiritual_upright
        self.spiritual_reversed = spiritual_reversed
        self.shadow_aspect = shadow_aspect

    def __str__(self):
        return "CardFacets(general_upright={}, general_reversed={}, love_upright={}, love_reversed={}, career_upright={}, career_reversed={}, spiritual_upright={}, spiritual_reversed={}, shadow_aspect={})".format(self.general_upright, self.general_reversed, self.love_upright, self.love_reversed, self.career_upright, self.career_reversed, self.spiritual_upright, self.spiritual_reversed, self.shadow_aspect)

    def __eq__(self, other):
        if self.general_upright != other.general_upright:
            return False
        if self.general_reversed != other.general_reversed:
            return False
        if self.love_upright != other.love_upright:
            return False
        if self.love_reversed != other.love_reversed:
            return False
        if self.career_upright != other.career_upright:
            return False
        if self.career_reversed != other.career_reversed:
            return False
        if self.spiritual_upright != other.spiritual_upright:
            return False
        if self.spiritual_reversed != other.spiritual_reversed:
            return False
        if self.shadow_aspect != other.shadow_aspect:
            return False
        return True

class _UniffiConverterTypeCardFacets(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return CardFacets(
            general_upright=_UniffiConverterSequenceString.read(buf),
            general_reversed=_UniffiConverterSequenceString.read(buf),
            love_upright=_UniffiConverterString.read(buf),
            love_reversed=_UniffiConverterString.read(buf),
            career_upright=_UniffiConverterString.read(buf),
            career_reversed=_UniffiConverterString.read(buf),
            spiritual_upright=_UniffiConverterString.read(buf),
            spiritual_reversed=_UniffiConverterString.read(buf),
            shadow_aspect=_UniffiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterSequenceString.check_lower(value.general_upright)
        _UniffiConverterSequenceString.check_lower(value.general_reversed)
        _UniffiConverterString.check_lower(value.love_upright)
        _UniffiConverterString.check_lower(value.love_reversed)
        _UniffiConverterString.check_lower(value.career_upright)
        _UniffiConverterString.check_lower(value.career_reversed)
        _UniffiConverterString.check_lower(value.spiritual_upright)
        _UniffiConverterString.check_lower(value.spiritual_reversed)
        _UniffiConverterString.check_lower(value.shadow_aspect)

    @staticmethod
    def write(value, buf):
        _UniffiConverterSequenceString.write(value.general_upright, buf)
        _UniffiConverterSequenceString.write(value.general_reversed, buf)
        _UniffiConverterString.write(value.love_upright, buf)
        _UniffiConverterString.write(value.love_reversed, buf)
        _UniffiConverterString.write(value.career_upright, buf)
        _UniffiConverterString.write(value.career_reversed, buf)
        _UniffiConverterString.write(value.spiritual_upright, buf)
        _UniffiConverterString.write(value.spiritual_reversed, buf)
        _UniffiConverterString.write(value.shadow_aspect, buf)


class DrawnCard:
    card_id: "int"
    orientation: "Orientation"
    draw_sequence: "int"
    def __init__(self, *, card_id: "int", orientation: "Orientation", draw_sequence: "int"):
        self.card_id = card_id
        self.orientation = orientation
        self.draw_sequence = draw_sequence

    def __str__(self):
        return "DrawnCard(card_id={}, orientation={}, draw_sequence={})".format(self.card_id, self.orientation, self.draw_sequence)

    def __eq__(self, other):
        if self.card_id != other.card_id:
            return False
        if self.orientation != other.orientation:
            return False
        if self.draw_sequence != other.draw_sequence:
            return False
        return True

class _UniffiConverterTypeDrawnCard(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return DrawnCard(
            card_id=_UniffiConverterUInt8.read(buf),
            orientation=_UniffiConverterTypeOrientation.read(buf),
            draw_sequence=_UniffiConverterUInt8.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt8.check_lower(value.card_id)
        _UniffiConverterTypeOrientation.check_lower(value.orientation)
        _UniffiConverterUInt8.check_lower(value.draw_sequence)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt8.write(value.card_id, buf)
        _UniffiConverterTypeOrientation.write(value.orientation, buf)
        _UniffiConverterUInt8.write(value.draw_sequence, buf)


class ElementalDignitySummary:
    fire_ratio: "float"
    water_ratio: "float"
    air_ratio: "float"
    earth_ratio: "float"
    major_ratio: "float"
    reversed_ratio: "float"
    dominant_element: "DominantElement"
    shadow_card_id: "typing.Optional[int]"
    balance_description_zh: "str"
    def __init__(self, *, fire_ratio: "float", water_ratio: "float", air_ratio: "float", earth_ratio: "float", major_ratio: "float", reversed_ratio: "float", dominant_element: "DominantElement", shadow_card_id: "typing.Optional[int]", balance_description_zh: "str"):
        self.fire_ratio = fire_ratio
        self.water_ratio = water_ratio
        self.air_ratio = air_ratio
        self.earth_ratio = earth_ratio
        self.major_ratio = major_ratio
        self.reversed_ratio = reversed_ratio
        self.dominant_element = dominant_element
        self.shadow_card_id = shadow_card_id
        self.balance_description_zh = balance_description_zh

    def __str__(self):
        return "ElementalDignitySummary(fire_ratio={}, water_ratio={}, air_ratio={}, earth_ratio={}, major_ratio={}, reversed_ratio={}, dominant_element={}, shadow_card_id={}, balance_description_zh={})".format(self.fire_ratio, self.water_ratio, self.air_ratio, self.earth_ratio, self.major_ratio, self.reversed_ratio, self.dominant_element, self.shadow_card_id, self.balance_description_zh)

    def __eq__(self, other):
        if self.fire_ratio != other.fire_ratio:
            return False
        if self.water_ratio != other.water_ratio:
            return False
        if self.air_ratio != other.air_ratio:
            return False
        if self.earth_ratio != other.earth_ratio:
            return False
        if self.major_ratio != other.major_ratio:
            return False
        if self.reversed_ratio != other.reversed_ratio:
            return False
        if self.dominant_element != other.dominant_element:
            return False
        if self.shadow_card_id != other.shadow_card_id:
            return False
        if self.balance_description_zh != other.balance_description_zh:
            return False
        return True

class _UniffiConverterTypeElementalDignitySummary(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ElementalDignitySummary(
            fire_ratio=_UniffiConverterFloat.read(buf),
            water_ratio=_UniffiConverterFloat.read(buf),
            air_ratio=_UniffiConverterFloat.read(buf),
            earth_ratio=_UniffiConverterFloat.read(buf),
            major_ratio=_UniffiConverterFloat.read(buf),
            reversed_ratio=_UniffiConverterFloat.read(buf),
            dominant_element=_UniffiConverterTypeDominantElement.read(buf),
            shadow_card_id=_UniffiConverterOptionalUInt8.read(buf),
            balance_description_zh=_UniffiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterFloat.check_lower(value.fire_ratio)
        _UniffiConverterFloat.check_lower(value.water_ratio)
        _UniffiConverterFloat.check_lower(value.air_ratio)
        _UniffiConverterFloat.check_lower(value.earth_ratio)
        _UniffiConverterFloat.check_lower(value.major_ratio)
        _UniffiConverterFloat.check_lower(value.reversed_ratio)
        _UniffiConverterTypeDominantElement.check_lower(value.dominant_element)
        _UniffiConverterOptionalUInt8.check_lower(value.shadow_card_id)
        _UniffiConverterString.check_lower(value.balance_description_zh)

    @staticmethod
    def write(value, buf):
        _UniffiConverterFloat.write(value.fire_ratio, buf)
        _UniffiConverterFloat.write(value.water_ratio, buf)
        _UniffiConverterFloat.write(value.air_ratio, buf)
        _UniffiConverterFloat.write(value.earth_ratio, buf)
        _UniffiConverterFloat.write(value.major_ratio, buf)
        _UniffiConverterFloat.write(value.reversed_ratio, buf)
        _UniffiConverterTypeDominantElement.write(value.dominant_element, buf)
        _UniffiConverterOptionalUInt8.write(value.shadow_card_id, buf)
        _UniffiConverterString.write(value.balance_description_zh, buf)


class PlacedCard:
    slot_id: "int"
    drawn_card: "DrawnCard"
    def __init__(self, *, slot_id: "int", drawn_card: "DrawnCard"):
        self.slot_id = slot_id
        self.drawn_card = drawn_card

    def __str__(self):
        return "PlacedCard(slot_id={}, drawn_card={})".format(self.slot_id, self.drawn_card)

    def __eq__(self, other):
        if self.slot_id != other.slot_id:
            return False
        if self.drawn_card != other.drawn_card:
            return False
        return True

class _UniffiConverterTypePlacedCard(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return PlacedCard(
            slot_id=_UniffiConverterUInt8.read(buf),
            drawn_card=_UniffiConverterTypeDrawnCard.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt8.check_lower(value.slot_id)
        _UniffiConverterTypeDrawnCard.check_lower(value.drawn_card)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt8.write(value.slot_id, buf)
        _UniffiConverterTypeDrawnCard.write(value.drawn_card, buf)


class ReadingSession:
    session_id: "str"
    created_at: "int"
    spread_id: "str"
    question: "typing.Optional[str]"
    rng_seed: "str"
    reversal_probability: "float"
    placed_cards: "typing.List[PlacedCard]"
    dignity_summary: "ElementalDignitySummary"
    user_notes: "typing.Optional[str]"
    tags: "typing.List[str]"
    ai_interpretation: "typing.Optional[str]"
    def __init__(self, *, session_id: "str", created_at: "int", spread_id: "str", question: "typing.Optional[str]", rng_seed: "str", reversal_probability: "float", placed_cards: "typing.List[PlacedCard]", dignity_summary: "ElementalDignitySummary", user_notes: "typing.Optional[str]", tags: "typing.List[str]", ai_interpretation: "typing.Optional[str]"):
        self.session_id = session_id
        self.created_at = created_at
        self.spread_id = spread_id
        self.question = question
        self.rng_seed = rng_seed
        self.reversal_probability = reversal_probability
        self.placed_cards = placed_cards
        self.dignity_summary = dignity_summary
        self.user_notes = user_notes
        self.tags = tags
        self.ai_interpretation = ai_interpretation

    def __str__(self):
        return "ReadingSession(session_id={}, created_at={}, spread_id={}, question={}, rng_seed={}, reversal_probability={}, placed_cards={}, dignity_summary={}, user_notes={}, tags={}, ai_interpretation={})".format(self.session_id, self.created_at, self.spread_id, self.question, self.rng_seed, self.reversal_probability, self.placed_cards, self.dignity_summary, self.user_notes, self.tags, self.ai_interpretation)

    def __eq__(self, other):
        if self.session_id != other.session_id:
            return False
        if self.created_at != other.created_at:
            return False
        if self.spread_id != other.spread_id:
            return False
        if self.question != other.question:
            return False
        if self.rng_seed != other.rng_seed:
            return False
        if self.reversal_probability != other.reversal_probability:
            return False
        if self.placed_cards != other.placed_cards:
            return False
        if self.dignity_summary != other.dignity_summary:
            return False
        if self.user_notes != other.user_notes:
            return False
        if self.tags != other.tags:
            return False
        if self.ai_interpretation != other.ai_interpretation:
            return False
        return True

class _UniffiConverterTypeReadingSession(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ReadingSession(
            session_id=_UniffiConverterString.read(buf),
            created_at=_UniffiConverterInt64.read(buf),
            spread_id=_UniffiConverterString.read(buf),
            question=_UniffiConverterOptionalString.read(buf),
            rng_seed=_UniffiConverterString.read(buf),
            reversal_probability=_UniffiConverterFloat.read(buf),
            placed_cards=_UniffiConverterSequenceTypePlacedCard.read(buf),
            dignity_summary=_UniffiConverterTypeElementalDignitySummary.read(buf),
            user_notes=_UniffiConverterOptionalString.read(buf),
            tags=_UniffiConverterSequenceString.read(buf),
            ai_interpretation=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.session_id)
        _UniffiConverterInt64.check_lower(value.created_at)
        _UniffiConverterString.check_lower(value.spread_id)
        _UniffiConverterOptionalString.check_lower(value.question)
        _UniffiConverterString.check_lower(value.rng_seed)
        _UniffiConverterFloat.check_lower(value.reversal_probability)
        _UniffiConverterSequenceTypePlacedCard.check_lower(value.placed_cards)
        _UniffiConverterTypeElementalDignitySummary.check_lower(value.dignity_summary)
        _UniffiConverterOptionalString.check_lower(value.user_notes)
        _UniffiConverterSequenceString.check_lower(value.tags)
        _UniffiConverterOptionalString.check_lower(value.ai_interpretation)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.session_id, buf)
        _UniffiConverterInt64.write(value.created_at, buf)
        _UniffiConverterString.write(value.spread_id, buf)
        _UniffiConverterOptionalString.write(value.question, buf)
        _UniffiConverterString.write(value.rng_seed, buf)
        _UniffiConverterFloat.write(value.reversal_probability, buf)
        _UniffiConverterSequenceTypePlacedCard.write(value.placed_cards, buf)
        _UniffiConverterTypeElementalDignitySummary.write(value.dignity_summary, buf)
        _UniffiConverterOptionalString.write(value.user_notes, buf)
        _UniffiConverterSequenceString.write(value.tags, buf)
        _UniffiConverterOptionalString.write(value.ai_interpretation, buf)


class Spread:
    id: "str"
    name_en: "str"
    name_zh: "str"
    description: "str"
    category: "SpreadCategory"
    slots: "typing.List[SpreadSlot]"
    def __init__(self, *, id: "str", name_en: "str", name_zh: "str", description: "str", category: "SpreadCategory", slots: "typing.List[SpreadSlot]"):
        self.id = id
        self.name_en = name_en
        self.name_zh = name_zh
        self.description = description
        self.category = category
        self.slots = slots

    def __str__(self):
        return "Spread(id={}, name_en={}, name_zh={}, description={}, category={}, slots={})".format(self.id, self.name_en, self.name_zh, self.description, self.category, self.slots)

    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.name_en != other.name_en:
            return False
        if self.name_zh != other.name_zh:
            return False
        if self.description != other.description:
            return False
        if self.category != other.category:
            return False
        if self.slots != other.slots:
            return False
        return True

class _UniffiConverterTypeSpread(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Spread(
            id=_UniffiConverterString.read(buf),
            name_en=_UniffiConverterString.read(buf),
            name_zh=_UniffiConverterString.read(buf),
            description=_UniffiConverterString.read(buf),
            category=_UniffiConverterTypeSpreadCategory.read(buf),
            slots=_UniffiConverterSequenceTypeSpreadSlot.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.id)
        _UniffiConverterString.check_lower(value.name_en)
        _UniffiConverterString.check_lower(value.name_zh)
        _UniffiConverterString.check_lower(value.description)
        _UniffiConverterTypeSpreadCategory.check_lower(value.category)
        _UniffiConverterSequenceTypeSpreadSlot.check_lower(value.slots)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.id, buf)
        _UniffiConverterString.write(value.name_en, buf)
        _UniffiConverterString.write(value.name_zh, buf)
        _UniffiConverterString.write(value.description, buf)
        _UniffiConverterTypeSpreadCategory.write(value.category, buf)
        _UniffiConverterSequenceTypeSpreadSlot.write(value.slots, buf)


class SpreadSlot:
    slot_id: "int"
    title_en: "str"
    title_zh: "str"
    meaning_prompt: "str"
    x: "float"
    y: "float"
    rotation_deg: "float"
    z_index: "int"
    constraint: "SlotConstraint"
    def __init__(self, *, slot_id: "int", title_en: "str", title_zh: "str", meaning_prompt: "str", x: "float", y: "float", rotation_deg: "float", z_index: "int", constraint: "SlotConstraint"):
        self.slot_id = slot_id
        self.title_en = title_en
        self.title_zh = title_zh
        self.meaning_prompt = meaning_prompt
        self.x = x
        self.y = y
        self.rotation_deg = rotation_deg
        self.z_index = z_index
        self.constraint = constraint

    def __str__(self):
        return "SpreadSlot(slot_id={}, title_en={}, title_zh={}, meaning_prompt={}, x={}, y={}, rotation_deg={}, z_index={}, constraint={})".format(self.slot_id, self.title_en, self.title_zh, self.meaning_prompt, self.x, self.y, self.rotation_deg, self.z_index, self.constraint)

    def __eq__(self, other):
        if self.slot_id != other.slot_id:
            return False
        if self.title_en != other.title_en:
            return False
        if self.title_zh != other.title_zh:
            return False
        if self.meaning_prompt != other.meaning_prompt:
            return False
        if self.x != other.x:
            return False
        if self.y != other.y:
            return False
        if self.rotation_deg != other.rotation_deg:
            return False
        if self.z_index != other.z_index:
            return False
        if self.constraint != other.constraint:
            return False
        return True

class _UniffiConverterTypeSpreadSlot(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return SpreadSlot(
            slot_id=_UniffiConverterUInt8.read(buf),
            title_en=_UniffiConverterString.read(buf),
            title_zh=_UniffiConverterString.read(buf),
            meaning_prompt=_UniffiConverterString.read(buf),
            x=_UniffiConverterFloat.read(buf),
            y=_UniffiConverterFloat.read(buf),
            rotation_deg=_UniffiConverterFloat.read(buf),
            z_index=_UniffiConverterInt16.read(buf),
            constraint=_UniffiConverterTypeSlotConstraint.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterUInt8.check_lower(value.slot_id)
        _UniffiConverterString.check_lower(value.title_en)
        _UniffiConverterString.check_lower(value.title_zh)
        _UniffiConverterString.check_lower(value.meaning_prompt)
        _UniffiConverterFloat.check_lower(value.x)
        _UniffiConverterFloat.check_lower(value.y)
        _UniffiConverterFloat.check_lower(value.rotation_deg)
        _UniffiConverterInt16.check_lower(value.z_index)
        _UniffiConverterTypeSlotConstraint.check_lower(value.constraint)

    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt8.write(value.slot_id, buf)
        _UniffiConverterString.write(value.title_en, buf)
        _UniffiConverterString.write(value.title_zh, buf)
        _UniffiConverterString.write(value.meaning_prompt, buf)
        _UniffiConverterFloat.write(value.x, buf)
        _UniffiConverterFloat.write(value.y, buf)
        _UniffiConverterFloat.write(value.rotation_deg, buf)
        _UniffiConverterInt16.write(value.z_index, buf)
        _UniffiConverterTypeSlotConstraint.write(value.constraint, buf)





class ArcanaType(enum.Enum):
    MAJOR = 0
    
    MINOR = 1
    


class _UniffiConverterTypeArcanaType(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return ArcanaType.MAJOR
        if variant == 2:
            return ArcanaType.MINOR
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == ArcanaType.MAJOR:
            return
        if value == ArcanaType.MINOR:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == ArcanaType.MAJOR:
            buf.write_i32(1)
        if value == ArcanaType.MINOR:
            buf.write_i32(2)







class DominantElement(enum.Enum):
    FIRE = 0
    
    WATER = 1
    
    AIR = 2
    
    EARTH = 3
    
    BALANCED = 4
    
    NONE = 5
    


class _UniffiConverterTypeDominantElement(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return DominantElement.FIRE
        if variant == 2:
            return DominantElement.WATER
        if variant == 3:
            return DominantElement.AIR
        if variant == 4:
            return DominantElement.EARTH
        if variant == 5:
            return DominantElement.BALANCED
        if variant == 6:
            return DominantElement.NONE
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == DominantElement.FIRE:
            return
        if value == DominantElement.WATER:
            return
        if value == DominantElement.AIR:
            return
        if value == DominantElement.EARTH:
            return
        if value == DominantElement.BALANCED:
            return
        if value == DominantElement.NONE:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == DominantElement.FIRE:
            buf.write_i32(1)
        if value == DominantElement.WATER:
            buf.write_i32(2)
        if value == DominantElement.AIR:
            buf.write_i32(3)
        if value == DominantElement.EARTH:
            buf.write_i32(4)
        if value == DominantElement.BALANCED:
            buf.write_i32(5)
        if value == DominantElement.NONE:
            buf.write_i32(6)







class Element(enum.Enum):
    FIRE = 0
    
    WATER = 1
    
    AIR = 2
    
    EARTH = 3
    
    SPIRIT = 4
    
    NONE = 5
    


class _UniffiConverterTypeElement(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Element.FIRE
        if variant == 2:
            return Element.WATER
        if variant == 3:
            return Element.AIR
        if variant == 4:
            return Element.EARTH
        if variant == 5:
            return Element.SPIRIT
        if variant == 6:
            return Element.NONE
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Element.FIRE:
            return
        if value == Element.WATER:
            return
        if value == Element.AIR:
            return
        if value == Element.EARTH:
            return
        if value == Element.SPIRIT:
            return
        if value == Element.NONE:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Element.FIRE:
            buf.write_i32(1)
        if value == Element.WATER:
            buf.write_i32(2)
        if value == Element.AIR:
            buf.write_i32(3)
        if value == Element.EARTH:
            buf.write_i32(4)
        if value == Element.SPIRIT:
            buf.write_i32(5)
        if value == Element.NONE:
            buf.write_i32(6)







class Orientation(enum.Enum):
    UPRIGHT = 0
    
    REVERSED = 1
    


class _UniffiConverterTypeOrientation(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Orientation.UPRIGHT
        if variant == 2:
            return Orientation.REVERSED
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Orientation.UPRIGHT:
            return
        if value == Orientation.REVERSED:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Orientation.UPRIGHT:
            buf.write_i32(1)
        if value == Orientation.REVERSED:
            buf.write_i32(2)







class Rank(enum.Enum):
    ACE = 1
    
    TWO = 2
    
    THREE = 3
    
    FOUR = 4
    
    FIVE = 5
    
    SIX = 6
    
    SEVEN = 7
    
    EIGHT = 8
    
    NINE = 9
    
    TEN = 10
    
    PAGE = 11
    
    KNIGHT = 12
    
    QUEEN = 13
    
    KING = 14
    


class _UniffiConverterTypeRank(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Rank.ACE
        if variant == 2:
            return Rank.TWO
        if variant == 3:
            return Rank.THREE
        if variant == 4:
            return Rank.FOUR
        if variant == 5:
            return Rank.FIVE
        if variant == 6:
            return Rank.SIX
        if variant == 7:
            return Rank.SEVEN
        if variant == 8:
            return Rank.EIGHT
        if variant == 9:
            return Rank.NINE
        if variant == 10:
            return Rank.TEN
        if variant == 11:
            return Rank.PAGE
        if variant == 12:
            return Rank.KNIGHT
        if variant == 13:
            return Rank.QUEEN
        if variant == 14:
            return Rank.KING
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Rank.ACE:
            return
        if value == Rank.TWO:
            return
        if value == Rank.THREE:
            return
        if value == Rank.FOUR:
            return
        if value == Rank.FIVE:
            return
        if value == Rank.SIX:
            return
        if value == Rank.SEVEN:
            return
        if value == Rank.EIGHT:
            return
        if value == Rank.NINE:
            return
        if value == Rank.TEN:
            return
        if value == Rank.PAGE:
            return
        if value == Rank.KNIGHT:
            return
        if value == Rank.QUEEN:
            return
        if value == Rank.KING:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Rank.ACE:
            buf.write_i32(1)
        if value == Rank.TWO:
            buf.write_i32(2)
        if value == Rank.THREE:
            buf.write_i32(3)
        if value == Rank.FOUR:
            buf.write_i32(4)
        if value == Rank.FIVE:
            buf.write_i32(5)
        if value == Rank.SIX:
            buf.write_i32(6)
        if value == Rank.SEVEN:
            buf.write_i32(7)
        if value == Rank.EIGHT:
            buf.write_i32(8)
        if value == Rank.NINE:
            buf.write_i32(9)
        if value == Rank.TEN:
            buf.write_i32(10)
        if value == Rank.PAGE:
            buf.write_i32(11)
        if value == Rank.KNIGHT:
            buf.write_i32(12)
        if value == Rank.QUEEN:
            buf.write_i32(13)
        if value == Rank.KING:
            buf.write_i32(14)







class SlotConstraint(enum.Enum):
    ANY = 0
    
    MAJOR_ONLY = 1
    
    MINOR_ONLY = 2
    
    WANDS_ONLY = 3
    
    CUPS_ONLY = 4
    
    SWORDS_ONLY = 5
    
    PENTACLES_ONLY = 6
    


class _UniffiConverterTypeSlotConstraint(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return SlotConstraint.ANY
        if variant == 2:
            return SlotConstraint.MAJOR_ONLY
        if variant == 3:
            return SlotConstraint.MINOR_ONLY
        if variant == 4:
            return SlotConstraint.WANDS_ONLY
        if variant == 5:
            return SlotConstraint.CUPS_ONLY
        if variant == 6:
            return SlotConstraint.SWORDS_ONLY
        if variant == 7:
            return SlotConstraint.PENTACLES_ONLY
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == SlotConstraint.ANY:
            return
        if value == SlotConstraint.MAJOR_ONLY:
            return
        if value == SlotConstraint.MINOR_ONLY:
            return
        if value == SlotConstraint.WANDS_ONLY:
            return
        if value == SlotConstraint.CUPS_ONLY:
            return
        if value == SlotConstraint.SWORDS_ONLY:
            return
        if value == SlotConstraint.PENTACLES_ONLY:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == SlotConstraint.ANY:
            buf.write_i32(1)
        if value == SlotConstraint.MAJOR_ONLY:
            buf.write_i32(2)
        if value == SlotConstraint.MINOR_ONLY:
            buf.write_i32(3)
        if value == SlotConstraint.WANDS_ONLY:
            buf.write_i32(4)
        if value == SlotConstraint.CUPS_ONLY:
            buf.write_i32(5)
        if value == SlotConstraint.SWORDS_ONLY:
            buf.write_i32(6)
        if value == SlotConstraint.PENTACLES_ONLY:
            buf.write_i32(7)







class SpreadCategory(enum.Enum):
    DAILY = 0
    
    DECISION = 1
    
    RELATIONSHIP = 2
    
    COMPREHENSIVE = 3
    
    CUSTOM = 4
    


class _UniffiConverterTypeSpreadCategory(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return SpreadCategory.DAILY
        if variant == 2:
            return SpreadCategory.DECISION
        if variant == 3:
            return SpreadCategory.RELATIONSHIP
        if variant == 4:
            return SpreadCategory.COMPREHENSIVE
        if variant == 5:
            return SpreadCategory.CUSTOM
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == SpreadCategory.DAILY:
            return
        if value == SpreadCategory.DECISION:
            return
        if value == SpreadCategory.RELATIONSHIP:
            return
        if value == SpreadCategory.COMPREHENSIVE:
            return
        if value == SpreadCategory.CUSTOM:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == SpreadCategory.DAILY:
            buf.write_i32(1)
        if value == SpreadCategory.DECISION:
            buf.write_i32(2)
        if value == SpreadCategory.RELATIONSHIP:
            buf.write_i32(3)
        if value == SpreadCategory.COMPREHENSIVE:
            buf.write_i32(4)
        if value == SpreadCategory.CUSTOM:
            buf.write_i32(5)







class Suit(enum.Enum):
    WANDS = 0
    
    CUPS = 1
    
    SWORDS = 2
    
    PENTACLES = 3
    


class _UniffiConverterTypeSuit(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Suit.WANDS
        if variant == 2:
            return Suit.CUPS
        if variant == 3:
            return Suit.SWORDS
        if variant == 4:
            return Suit.PENTACLES
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Suit.WANDS:
            return
        if value == Suit.CUPS:
            return
        if value == Suit.SWORDS:
            return
        if value == Suit.PENTACLES:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Suit.WANDS:
            buf.write_i32(1)
        if value == Suit.CUPS:
            buf.write_i32(2)
        if value == Suit.SWORDS:
            buf.write_i32(3)
        if value == Suit.PENTACLES:
            buf.write_i32(4)




# TarotError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class TarotError(Exception):
    pass

_UniffiTempTarotError = TarotError

class TarotError:  # type: ignore
    class InvalidSeed(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.InvalidSeed({})".format(str(self))
    _UniffiTempTarotError.InvalidSeed = InvalidSeed # type: ignore
    class CardIndexOutOfBounds(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], int):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'int', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.CardIndexOutOfBounds({})".format(str(self))
    _UniffiTempTarotError.CardIndexOutOfBounds = CardIndexOutOfBounds # type: ignore
    class DuplicateCardDraw(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], int):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'int', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.DuplicateCardDraw({})".format(str(self))
    _UniffiTempTarotError.DuplicateCardDraw = DuplicateCardDraw # type: ignore
    class SpreadSlotOverflow(_UniffiTempTarotError):
        def __init__(self, requested, capacity):
            super().__init__(", ".join([
                "requested={!r}".format(requested),
                "capacity={!r}".format(capacity),
            ]))
            self.requested = requested
            self.capacity = capacity

        def __repr__(self):
            return "TarotError.SpreadSlotOverflow({})".format(str(self))
    _UniffiTempTarotError.SpreadSlotOverflow = SpreadSlotOverflow # type: ignore
    class ConstraintViolation(_UniffiTempTarotError):
        def __init__(self, slot_id, required, actual):
            super().__init__(", ".join([
                "slot_id={!r}".format(slot_id),
                "required={!r}".format(required),
                "actual={!r}".format(actual),
            ]))
            self.slot_id = slot_id
            self.required = required
            self.actual = actual

        def __repr__(self):
            return "TarotError.ConstraintViolation({})".format(str(self))
    _UniffiTempTarotError.ConstraintViolation = ConstraintViolation # type: ignore
    class SpreadNotFound(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.SpreadNotFound({})".format(str(self))
    _UniffiTempTarotError.SpreadNotFound = SpreadNotFound # type: ignore
    class DeserializationError(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.DeserializationError({})".format(str(self))
    _UniffiTempTarotError.DeserializationError = DeserializationError # type: ignore
    class AiProviderUnavailable(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.AiProviderUnavailable({})".format(str(self))
    _UniffiTempTarotError.AiProviderUnavailable = AiProviderUnavailable # type: ignore
    class Unauthorized(_UniffiTempTarotError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "TarotError.Unauthorized({})".format(str(self))
    _UniffiTempTarotError.Unauthorized = Unauthorized # type: ignore

TarotError = _UniffiTempTarotError # type: ignore
del _UniffiTempTarotError


class _UniffiConverterTypeTarotError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return TarotError.InvalidSeed(
                _UniffiConverterString.read(buf),
            )
        if variant == 2:
            return TarotError.CardIndexOutOfBounds(
                _UniffiConverterUInt8.read(buf),
            )
        if variant == 3:
            return TarotError.DuplicateCardDraw(
                _UniffiConverterUInt8.read(buf),
            )
        if variant == 4:
            return TarotError.SpreadSlotOverflow(
                _UniffiConverterUInt64.read(buf),
                _UniffiConverterUInt64.read(buf),
            )
        if variant == 5:
            return TarotError.ConstraintViolation(
                _UniffiConverterUInt8.read(buf),
                _UniffiConverterString.read(buf),
                _UniffiConverterString.read(buf),
            )
        if variant == 6:
            return TarotError.SpreadNotFound(
                _UniffiConverterString.read(buf),
            )
        if variant == 7:
            return TarotError.DeserializationError(
                _UniffiConverterString.read(buf),
            )
        if variant == 8:
            return TarotError.AiProviderUnavailable(
                _UniffiConverterString.read(buf),
            )
        if variant == 9:
            return TarotError.Unauthorized(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, TarotError.InvalidSeed):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.CardIndexOutOfBounds):
            _UniffiConverterUInt8.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.DuplicateCardDraw):
            _UniffiConverterUInt8.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.SpreadSlotOverflow):
            _UniffiConverterUInt64.check_lower(value.requested)
            _UniffiConverterUInt64.check_lower(value.capacity)
            return
        if isinstance(value, TarotError.ConstraintViolation):
            _UniffiConverterUInt8.check_lower(value.slot_id)
            _UniffiConverterString.check_lower(value.required)
            _UniffiConverterString.check_lower(value.actual)
            return
        if isinstance(value, TarotError.SpreadNotFound):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.DeserializationError):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.AiProviderUnavailable):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, TarotError.Unauthorized):
            _UniffiConverterString.check_lower(value._values[0])
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, TarotError.InvalidSeed):
            buf.write_i32(1)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, TarotError.CardIndexOutOfBounds):
            buf.write_i32(2)
            _UniffiConverterUInt8.write(value._values[0], buf)
        if isinstance(value, TarotError.DuplicateCardDraw):
            buf.write_i32(3)
            _UniffiConverterUInt8.write(value._values[0], buf)
        if isinstance(value, TarotError.SpreadSlotOverflow):
            buf.write_i32(4)
            _UniffiConverterUInt64.write(value.requested, buf)
            _UniffiConverterUInt64.write(value.capacity, buf)
        if isinstance(value, TarotError.ConstraintViolation):
            buf.write_i32(5)
            _UniffiConverterUInt8.write(value.slot_id, buf)
            _UniffiConverterString.write(value.required, buf)
            _UniffiConverterString.write(value.actual, buf)
        if isinstance(value, TarotError.SpreadNotFound):
            buf.write_i32(6)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, TarotError.DeserializationError):
            buf.write_i32(7)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, TarotError.AiProviderUnavailable):
            buf.write_i32(8)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, TarotError.Unauthorized):
            buf.write_i32(9)
            _UniffiConverterString.write(value._values[0], buf)



class _UniffiConverterOptionalUInt8(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterUInt8.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterUInt8.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterUInt8.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeRank(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeRank.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeRank.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeRank.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeSuit(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeSuit.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeSuit.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeSuit.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterString.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeCard(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeCard.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeCard.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeCard.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypePlacedCard(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypePlacedCard.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypePlacedCard.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypePlacedCard.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeSpread(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeSpread.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeSpread.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeSpread.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeSpreadSlot(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeSpreadSlot.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeSpreadSlot.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeSpreadSlot.read(buf) for i in range(count)
        ]

# Async support

def draw_reading_session(spread_id: "str",question: "typing.Optional[str]",seed_hex: "typing.Optional[str]",reversal_rate: "float") -> "ReadingSession":
    """
    UniFFI Exported: Draws a deterministic reading session
    """

    _UniffiConverterString.check_lower(spread_id)
    
    _UniffiConverterOptionalString.check_lower(question)
    
    _UniffiConverterOptionalString.check_lower(seed_hex)
    
    _UniffiConverterFloat.check_lower(reversal_rate)
    
    return _UniffiConverterTypeReadingSession.lift(_uniffi_rust_call_with_error(_UniffiConverterTypeTarotError,_UniffiLib.uniffi_taroturn_core_fn_func_draw_reading_session,
        _UniffiConverterString.lower(spread_id),
        _UniffiConverterOptionalString.lower(question),
        _UniffiConverterOptionalString.lower(seed_hex),
        _UniffiConverterFloat.lower(reversal_rate)))


def generate_random_seed() -> "str":
    """
    UniFFI Exported: Generates a 64-character cryptographic CSPRNG seed
    """

    return _UniffiConverterString.lift(_uniffi_rust_call_with_error(_UniffiConverterTypeTarotError,_UniffiLib.uniffi_taroturn_core_fn_func_generate_random_seed,))


def get_card_by_id(card_id: "int") -> "Card":
    """
    UniFFI Exported: Retrieves a card archetype definition by card ID (0..77)
    """

    _UniffiConverterUInt8.check_lower(card_id)
    
    return _UniffiConverterTypeCard.lift(_uniffi_rust_call_with_error(_UniffiConverterTypeTarotError,_UniffiLib.uniffi_taroturn_core_fn_func_get_card_by_id,
        _UniffiConverterUInt8.lower(card_id)))


def get_taroturn_version() -> "str":
    """
    UniFFI Exported: Returns static library version string
    """

    return _UniffiConverterString.lift(_uniffi_rust_call(_UniffiLib.uniffi_taroturn_core_fn_func_get_taroturn_version,))


def list_all_cards() -> "typing.List[Card]":
    """
    UniFFI Exported: Lists all 78 standard Tarot cards
    """

    return _UniffiConverterSequenceTypeCard.lift(_uniffi_rust_call(_UniffiLib.uniffi_taroturn_core_fn_func_list_all_cards,))


def list_canonical_spreads() -> "typing.List[Spread]":
    """
    UniFFI Exported: Lists all built-in canonical spreads
    """

    return _UniffiConverterSequenceTypeSpread.lift(_uniffi_rust_call(_UniffiLib.uniffi_taroturn_core_fn_func_list_canonical_spreads,))


__all__ = [
    "InternalError",
    "ArcanaType",
    "DominantElement",
    "Element",
    "Orientation",
    "Rank",
    "SlotConstraint",
    "SpreadCategory",
    "Suit",
    "TarotError",
    "Card",
    "CardFacets",
    "DrawnCard",
    "ElementalDignitySummary",
    "PlacedCard",
    "ReadingSession",
    "Spread",
    "SpreadSlot",
    "draw_reading_session",
    "generate_random_seed",
    "get_card_by_id",
    "get_taroturn_version",
    "list_all_cards",
    "list_canonical_spreads",
]

