// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.taroturn_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_taroturn_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_taroturn_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "taroturn_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}






































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "taroturn_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_taroturn_core_fn_func_draw_reading_session(`spreadId`: RustBuffer.ByValue,`question`: RustBuffer.ByValue,`seedHex`: RustBuffer.ByValue,`reversalRate`: Float,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_taroturn_core_fn_func_generate_random_seed(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_taroturn_core_fn_func_get_card_by_id(`cardId`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_taroturn_core_fn_func_get_taroturn_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_taroturn_core_fn_func_list_all_cards(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_taroturn_core_fn_func_list_canonical_spreads(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_taroturn_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_taroturn_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_taroturn_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_taroturn_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_taroturn_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_taroturn_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_taroturn_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_taroturn_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_taroturn_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_taroturn_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_taroturn_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_taroturn_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_taroturn_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_taroturn_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_taroturn_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_taroturn_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_taroturn_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_taroturn_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_taroturn_core_checksum_func_draw_reading_session(
    ): Short
    fun uniffi_taroturn_core_checksum_func_generate_random_seed(
    ): Short
    fun uniffi_taroturn_core_checksum_func_get_card_by_id(
    ): Short
    fun uniffi_taroturn_core_checksum_func_get_taroturn_version(
    ): Short
    fun uniffi_taroturn_core_checksum_func_list_all_cards(
    ): Short
    fun uniffi_taroturn_core_checksum_func_list_canonical_spreads(
    ): Short
    fun ffi_taroturn_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_taroturn_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_taroturn_core_checksum_func_draw_reading_session() != 40058.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_taroturn_core_checksum_func_generate_random_seed() != 18692.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_taroturn_core_checksum_func_get_card_by_id() != 62755.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_taroturn_core_checksum_func_get_taroturn_version() != 63623.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_taroturn_core_checksum_func_list_all_cards() != 52176.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_taroturn_core_checksum_func_list_canonical_spreads() != 59923.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterShort: FfiConverter<Short, Short> {
    override fun lift(value: Short): Short {
        return value
    }

    override fun read(buf: ByteBuffer): Short {
        return buf.getShort()
    }

    override fun lower(value: Short): Short {
        return value
    }

    override fun allocationSize(value: Short) = 2UL

    override fun write(value: Short, buf: ByteBuffer) {
        buf.putShort(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class Card (
    var `id`: kotlin.UByte, 
    var `key`: kotlin.String, 
    var `arcana`: ArcanaType, 
    var `suit`: Suit?, 
    var `rank`: Rank?, 
    var `element`: Element, 
    var `nameEn`: kotlin.String, 
    var `nameZh`: kotlin.String, 
    var `astrology`: kotlin.String?, 
    var `hebrewLetter`: kotlin.String?, 
    var `facets`: CardFacets
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCard: FfiConverterRustBuffer<Card> {
    override fun read(buf: ByteBuffer): Card {
        return Card(
            FfiConverterUByte.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeArcanaType.read(buf),
            FfiConverterOptionalTypeSuit.read(buf),
            FfiConverterOptionalTypeRank.read(buf),
            FfiConverterTypeElement.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterTypeCardFacets.read(buf),
        )
    }

    override fun allocationSize(value: Card) = (
            FfiConverterUByte.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`key`) +
            FfiConverterTypeArcanaType.allocationSize(value.`arcana`) +
            FfiConverterOptionalTypeSuit.allocationSize(value.`suit`) +
            FfiConverterOptionalTypeRank.allocationSize(value.`rank`) +
            FfiConverterTypeElement.allocationSize(value.`element`) +
            FfiConverterString.allocationSize(value.`nameEn`) +
            FfiConverterString.allocationSize(value.`nameZh`) +
            FfiConverterOptionalString.allocationSize(value.`astrology`) +
            FfiConverterOptionalString.allocationSize(value.`hebrewLetter`) +
            FfiConverterTypeCardFacets.allocationSize(value.`facets`)
    )

    override fun write(value: Card, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`id`, buf)
            FfiConverterString.write(value.`key`, buf)
            FfiConverterTypeArcanaType.write(value.`arcana`, buf)
            FfiConverterOptionalTypeSuit.write(value.`suit`, buf)
            FfiConverterOptionalTypeRank.write(value.`rank`, buf)
            FfiConverterTypeElement.write(value.`element`, buf)
            FfiConverterString.write(value.`nameEn`, buf)
            FfiConverterString.write(value.`nameZh`, buf)
            FfiConverterOptionalString.write(value.`astrology`, buf)
            FfiConverterOptionalString.write(value.`hebrewLetter`, buf)
            FfiConverterTypeCardFacets.write(value.`facets`, buf)
    }
}



data class CardFacets (
    var `generalUpright`: List<kotlin.String>, 
    var `generalReversed`: List<kotlin.String>, 
    var `loveUpright`: kotlin.String, 
    var `loveReversed`: kotlin.String, 
    var `careerUpright`: kotlin.String, 
    var `careerReversed`: kotlin.String, 
    var `spiritualUpright`: kotlin.String, 
    var `spiritualReversed`: kotlin.String, 
    var `shadowAspect`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCardFacets: FfiConverterRustBuffer<CardFacets> {
    override fun read(buf: ByteBuffer): CardFacets {
        return CardFacets(
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: CardFacets) = (
            FfiConverterSequenceString.allocationSize(value.`generalUpright`) +
            FfiConverterSequenceString.allocationSize(value.`generalReversed`) +
            FfiConverterString.allocationSize(value.`loveUpright`) +
            FfiConverterString.allocationSize(value.`loveReversed`) +
            FfiConverterString.allocationSize(value.`careerUpright`) +
            FfiConverterString.allocationSize(value.`careerReversed`) +
            FfiConverterString.allocationSize(value.`spiritualUpright`) +
            FfiConverterString.allocationSize(value.`spiritualReversed`) +
            FfiConverterString.allocationSize(value.`shadowAspect`)
    )

    override fun write(value: CardFacets, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`generalUpright`, buf)
            FfiConverterSequenceString.write(value.`generalReversed`, buf)
            FfiConverterString.write(value.`loveUpright`, buf)
            FfiConverterString.write(value.`loveReversed`, buf)
            FfiConverterString.write(value.`careerUpright`, buf)
            FfiConverterString.write(value.`careerReversed`, buf)
            FfiConverterString.write(value.`spiritualUpright`, buf)
            FfiConverterString.write(value.`spiritualReversed`, buf)
            FfiConverterString.write(value.`shadowAspect`, buf)
    }
}



data class DrawnCard (
    var `cardId`: kotlin.UByte, 
    var `orientation`: Orientation, 
    var `drawSequence`: kotlin.UByte
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDrawnCard: FfiConverterRustBuffer<DrawnCard> {
    override fun read(buf: ByteBuffer): DrawnCard {
        return DrawnCard(
            FfiConverterUByte.read(buf),
            FfiConverterTypeOrientation.read(buf),
            FfiConverterUByte.read(buf),
        )
    }

    override fun allocationSize(value: DrawnCard) = (
            FfiConverterUByte.allocationSize(value.`cardId`) +
            FfiConverterTypeOrientation.allocationSize(value.`orientation`) +
            FfiConverterUByte.allocationSize(value.`drawSequence`)
    )

    override fun write(value: DrawnCard, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`cardId`, buf)
            FfiConverterTypeOrientation.write(value.`orientation`, buf)
            FfiConverterUByte.write(value.`drawSequence`, buf)
    }
}



data class ElementalDignitySummary (
    var `fireRatio`: kotlin.Float, 
    var `waterRatio`: kotlin.Float, 
    var `airRatio`: kotlin.Float, 
    var `earthRatio`: kotlin.Float, 
    var `majorRatio`: kotlin.Float, 
    var `reversedRatio`: kotlin.Float, 
    var `dominantElement`: DominantElement, 
    var `shadowCardId`: kotlin.UByte?, 
    var `balanceDescriptionZh`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeElementalDignitySummary: FfiConverterRustBuffer<ElementalDignitySummary> {
    override fun read(buf: ByteBuffer): ElementalDignitySummary {
        return ElementalDignitySummary(
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterTypeDominantElement.read(buf),
            FfiConverterOptionalUByte.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ElementalDignitySummary) = (
            FfiConverterFloat.allocationSize(value.`fireRatio`) +
            FfiConverterFloat.allocationSize(value.`waterRatio`) +
            FfiConverterFloat.allocationSize(value.`airRatio`) +
            FfiConverterFloat.allocationSize(value.`earthRatio`) +
            FfiConverterFloat.allocationSize(value.`majorRatio`) +
            FfiConverterFloat.allocationSize(value.`reversedRatio`) +
            FfiConverterTypeDominantElement.allocationSize(value.`dominantElement`) +
            FfiConverterOptionalUByte.allocationSize(value.`shadowCardId`) +
            FfiConverterString.allocationSize(value.`balanceDescriptionZh`)
    )

    override fun write(value: ElementalDignitySummary, buf: ByteBuffer) {
            FfiConverterFloat.write(value.`fireRatio`, buf)
            FfiConverterFloat.write(value.`waterRatio`, buf)
            FfiConverterFloat.write(value.`airRatio`, buf)
            FfiConverterFloat.write(value.`earthRatio`, buf)
            FfiConverterFloat.write(value.`majorRatio`, buf)
            FfiConverterFloat.write(value.`reversedRatio`, buf)
            FfiConverterTypeDominantElement.write(value.`dominantElement`, buf)
            FfiConverterOptionalUByte.write(value.`shadowCardId`, buf)
            FfiConverterString.write(value.`balanceDescriptionZh`, buf)
    }
}



data class PlacedCard (
    var `slotId`: kotlin.UByte, 
    var `drawnCard`: DrawnCard
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePlacedCard: FfiConverterRustBuffer<PlacedCard> {
    override fun read(buf: ByteBuffer): PlacedCard {
        return PlacedCard(
            FfiConverterUByte.read(buf),
            FfiConverterTypeDrawnCard.read(buf),
        )
    }

    override fun allocationSize(value: PlacedCard) = (
            FfiConverterUByte.allocationSize(value.`slotId`) +
            FfiConverterTypeDrawnCard.allocationSize(value.`drawnCard`)
    )

    override fun write(value: PlacedCard, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`slotId`, buf)
            FfiConverterTypeDrawnCard.write(value.`drawnCard`, buf)
    }
}



data class ReadingSession (
    var `sessionId`: kotlin.String, 
    var `createdAt`: kotlin.Long, 
    var `spreadId`: kotlin.String, 
    var `question`: kotlin.String?, 
    var `rngSeed`: kotlin.String, 
    var `reversalProbability`: kotlin.Float, 
    var `placedCards`: List<PlacedCard>, 
    var `dignitySummary`: ElementalDignitySummary, 
    var `userNotes`: kotlin.String?, 
    var `tags`: List<kotlin.String>, 
    var `aiInterpretation`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeReadingSession: FfiConverterRustBuffer<ReadingSession> {
    override fun read(buf: ByteBuffer): ReadingSession {
        return ReadingSession(
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterSequenceTypePlacedCard.read(buf),
            FfiConverterTypeElementalDignitySummary.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: ReadingSession) = (
            FfiConverterString.allocationSize(value.`sessionId`) +
            FfiConverterLong.allocationSize(value.`createdAt`) +
            FfiConverterString.allocationSize(value.`spreadId`) +
            FfiConverterOptionalString.allocationSize(value.`question`) +
            FfiConverterString.allocationSize(value.`rngSeed`) +
            FfiConverterFloat.allocationSize(value.`reversalProbability`) +
            FfiConverterSequenceTypePlacedCard.allocationSize(value.`placedCards`) +
            FfiConverterTypeElementalDignitySummary.allocationSize(value.`dignitySummary`) +
            FfiConverterOptionalString.allocationSize(value.`userNotes`) +
            FfiConverterSequenceString.allocationSize(value.`tags`) +
            FfiConverterOptionalString.allocationSize(value.`aiInterpretation`)
    )

    override fun write(value: ReadingSession, buf: ByteBuffer) {
            FfiConverterString.write(value.`sessionId`, buf)
            FfiConverterLong.write(value.`createdAt`, buf)
            FfiConverterString.write(value.`spreadId`, buf)
            FfiConverterOptionalString.write(value.`question`, buf)
            FfiConverterString.write(value.`rngSeed`, buf)
            FfiConverterFloat.write(value.`reversalProbability`, buf)
            FfiConverterSequenceTypePlacedCard.write(value.`placedCards`, buf)
            FfiConverterTypeElementalDignitySummary.write(value.`dignitySummary`, buf)
            FfiConverterOptionalString.write(value.`userNotes`, buf)
            FfiConverterSequenceString.write(value.`tags`, buf)
            FfiConverterOptionalString.write(value.`aiInterpretation`, buf)
    }
}



data class Spread (
    var `id`: kotlin.String, 
    var `nameEn`: kotlin.String, 
    var `nameZh`: kotlin.String, 
    var `description`: kotlin.String, 
    var `category`: SpreadCategory, 
    var `slots`: List<SpreadSlot>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSpread: FfiConverterRustBuffer<Spread> {
    override fun read(buf: ByteBuffer): Spread {
        return Spread(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeSpreadCategory.read(buf),
            FfiConverterSequenceTypeSpreadSlot.read(buf),
        )
    }

    override fun allocationSize(value: Spread) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`nameEn`) +
            FfiConverterString.allocationSize(value.`nameZh`) +
            FfiConverterString.allocationSize(value.`description`) +
            FfiConverterTypeSpreadCategory.allocationSize(value.`category`) +
            FfiConverterSequenceTypeSpreadSlot.allocationSize(value.`slots`)
    )

    override fun write(value: Spread, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`nameEn`, buf)
            FfiConverterString.write(value.`nameZh`, buf)
            FfiConverterString.write(value.`description`, buf)
            FfiConverterTypeSpreadCategory.write(value.`category`, buf)
            FfiConverterSequenceTypeSpreadSlot.write(value.`slots`, buf)
    }
}



data class SpreadSlot (
    var `slotId`: kotlin.UByte, 
    var `titleEn`: kotlin.String, 
    var `titleZh`: kotlin.String, 
    var `meaningPrompt`: kotlin.String, 
    var `x`: kotlin.Float, 
    var `y`: kotlin.Float, 
    var `rotationDeg`: kotlin.Float, 
    var `zIndex`: kotlin.Short, 
    var `constraint`: SlotConstraint
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSpreadSlot: FfiConverterRustBuffer<SpreadSlot> {
    override fun read(buf: ByteBuffer): SpreadSlot {
        return SpreadSlot(
            FfiConverterUByte.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterFloat.read(buf),
            FfiConverterShort.read(buf),
            FfiConverterTypeSlotConstraint.read(buf),
        )
    }

    override fun allocationSize(value: SpreadSlot) = (
            FfiConverterUByte.allocationSize(value.`slotId`) +
            FfiConverterString.allocationSize(value.`titleEn`) +
            FfiConverterString.allocationSize(value.`titleZh`) +
            FfiConverterString.allocationSize(value.`meaningPrompt`) +
            FfiConverterFloat.allocationSize(value.`x`) +
            FfiConverterFloat.allocationSize(value.`y`) +
            FfiConverterFloat.allocationSize(value.`rotationDeg`) +
            FfiConverterShort.allocationSize(value.`zIndex`) +
            FfiConverterTypeSlotConstraint.allocationSize(value.`constraint`)
    )

    override fun write(value: SpreadSlot, buf: ByteBuffer) {
            FfiConverterUByte.write(value.`slotId`, buf)
            FfiConverterString.write(value.`titleEn`, buf)
            FfiConverterString.write(value.`titleZh`, buf)
            FfiConverterString.write(value.`meaningPrompt`, buf)
            FfiConverterFloat.write(value.`x`, buf)
            FfiConverterFloat.write(value.`y`, buf)
            FfiConverterFloat.write(value.`rotationDeg`, buf)
            FfiConverterShort.write(value.`zIndex`, buf)
            FfiConverterTypeSlotConstraint.write(value.`constraint`, buf)
    }
}




enum class ArcanaType {
    
    MAJOR,
    MINOR;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeArcanaType: FfiConverterRustBuffer<ArcanaType> {
    override fun read(buf: ByteBuffer) = try {
        ArcanaType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ArcanaType) = 4UL

    override fun write(value: ArcanaType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class DominantElement {
    
    FIRE,
    WATER,
    AIR,
    EARTH,
    BALANCED,
    NONE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeDominantElement: FfiConverterRustBuffer<DominantElement> {
    override fun read(buf: ByteBuffer) = try {
        DominantElement.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: DominantElement) = 4UL

    override fun write(value: DominantElement, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Element {
    
    FIRE,
    WATER,
    AIR,
    EARTH,
    SPIRIT,
    NONE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeElement: FfiConverterRustBuffer<Element> {
    override fun read(buf: ByteBuffer) = try {
        Element.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Element) = 4UL

    override fun write(value: Element, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Orientation {
    
    UPRIGHT,
    REVERSED;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeOrientation: FfiConverterRustBuffer<Orientation> {
    override fun read(buf: ByteBuffer) = try {
        Orientation.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Orientation) = 4UL

    override fun write(value: Orientation, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Rank {
    
    ACE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEN,
    PAGE,
    KNIGHT,
    QUEEN,
    KING;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeRank: FfiConverterRustBuffer<Rank> {
    override fun read(buf: ByteBuffer) = try {
        Rank.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Rank) = 4UL

    override fun write(value: Rank, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class SlotConstraint {
    
    ANY,
    MAJOR_ONLY,
    MINOR_ONLY,
    WANDS_ONLY,
    CUPS_ONLY,
    SWORDS_ONLY,
    PENTACLES_ONLY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeSlotConstraint: FfiConverterRustBuffer<SlotConstraint> {
    override fun read(buf: ByteBuffer) = try {
        SlotConstraint.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: SlotConstraint) = 4UL

    override fun write(value: SlotConstraint, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class SpreadCategory {
    
    DAILY,
    DECISION,
    RELATIONSHIP,
    COMPREHENSIVE,
    CUSTOM;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeSpreadCategory: FfiConverterRustBuffer<SpreadCategory> {
    override fun read(buf: ByteBuffer) = try {
        SpreadCategory.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: SpreadCategory) = 4UL

    override fun write(value: SpreadCategory, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Suit {
    
    WANDS,
    CUPS,
    SWORDS,
    PENTACLES;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeSuit: FfiConverterRustBuffer<Suit> {
    override fun read(buf: ByteBuffer) = try {
        Suit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Suit) = 4UL

    override fun write(value: Suit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class TarotException: kotlin.Exception() {
    
    class InvalidSeed(
        
        val v1: kotlin.String
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class CardIndexOutOfBounds(
        
        val v1: kotlin.UByte
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class DuplicateCardDraw(
        
        val v1: kotlin.UByte
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class SpreadSlotOverflow(
        
        val `requested`: kotlin.ULong, 
        
        val `capacity`: kotlin.ULong
        ) : TarotException() {
        override val message
            get() = "requested=${ `requested` }, capacity=${ `capacity` }"
    }
    
    class ConstraintViolation(
        
        val `slotId`: kotlin.UByte, 
        
        val `required`: kotlin.String, 
        
        val `actual`: kotlin.String
        ) : TarotException() {
        override val message
            get() = "slotId=${ `slotId` }, required=${ `required` }, actual=${ `actual` }"
    }
    
    class SpreadNotFound(
        
        val v1: kotlin.String
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class DeserializationException(
        
        val v1: kotlin.String
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class AiProviderUnavailable(
        
        val v1: kotlin.String
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class Unauthorized(
        
        val v1: kotlin.String
        ) : TarotException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<TarotException> {
        override fun lift(error_buf: RustBuffer.ByValue): TarotException = FfiConverterTypeTarotError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeTarotError : FfiConverterRustBuffer<TarotException> {
    override fun read(buf: ByteBuffer): TarotException {
        

        return when(buf.getInt()) {
            1 -> TarotException.InvalidSeed(
                FfiConverterString.read(buf),
                )
            2 -> TarotException.CardIndexOutOfBounds(
                FfiConverterUByte.read(buf),
                )
            3 -> TarotException.DuplicateCardDraw(
                FfiConverterUByte.read(buf),
                )
            4 -> TarotException.SpreadSlotOverflow(
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                )
            5 -> TarotException.ConstraintViolation(
                FfiConverterUByte.read(buf),
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            6 -> TarotException.SpreadNotFound(
                FfiConverterString.read(buf),
                )
            7 -> TarotException.DeserializationException(
                FfiConverterString.read(buf),
                )
            8 -> TarotException.AiProviderUnavailable(
                FfiConverterString.read(buf),
                )
            9 -> TarotException.Unauthorized(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: TarotException): ULong {
        return when(value) {
            is TarotException.InvalidSeed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TarotException.CardIndexOutOfBounds -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUByte.allocationSize(value.v1)
            )
            is TarotException.DuplicateCardDraw -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUByte.allocationSize(value.v1)
            )
            is TarotException.SpreadSlotOverflow -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterULong.allocationSize(value.`requested`)
                + FfiConverterULong.allocationSize(value.`capacity`)
            )
            is TarotException.ConstraintViolation -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterUByte.allocationSize(value.`slotId`)
                + FfiConverterString.allocationSize(value.`required`)
                + FfiConverterString.allocationSize(value.`actual`)
            )
            is TarotException.SpreadNotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TarotException.DeserializationException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TarotException.AiProviderUnavailable -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is TarotException.Unauthorized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: TarotException, buf: ByteBuffer) {
        when(value) {
            is TarotException.InvalidSeed -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TarotException.CardIndexOutOfBounds -> {
                buf.putInt(2)
                FfiConverterUByte.write(value.v1, buf)
                Unit
            }
            is TarotException.DuplicateCardDraw -> {
                buf.putInt(3)
                FfiConverterUByte.write(value.v1, buf)
                Unit
            }
            is TarotException.SpreadSlotOverflow -> {
                buf.putInt(4)
                FfiConverterULong.write(value.`requested`, buf)
                FfiConverterULong.write(value.`capacity`, buf)
                Unit
            }
            is TarotException.ConstraintViolation -> {
                buf.putInt(5)
                FfiConverterUByte.write(value.`slotId`, buf)
                FfiConverterString.write(value.`required`, buf)
                FfiConverterString.write(value.`actual`, buf)
                Unit
            }
            is TarotException.SpreadNotFound -> {
                buf.putInt(6)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TarotException.DeserializationException -> {
                buf.putInt(7)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TarotException.AiProviderUnavailable -> {
                buf.putInt(8)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is TarotException.Unauthorized -> {
                buf.putInt(9)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalUByte: FfiConverterRustBuffer<kotlin.UByte?> {
    override fun read(buf: ByteBuffer): kotlin.UByte? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUByte.read(buf)
    }

    override fun allocationSize(value: kotlin.UByte?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUByte.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UByte?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUByte.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeRank: FfiConverterRustBuffer<Rank?> {
    override fun read(buf: ByteBuffer): Rank? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeRank.read(buf)
    }

    override fun allocationSize(value: Rank?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeRank.allocationSize(value)
        }
    }

    override fun write(value: Rank?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeRank.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeSuit: FfiConverterRustBuffer<Suit?> {
    override fun read(buf: ByteBuffer): Suit? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeSuit.read(buf)
    }

    override fun allocationSize(value: Suit?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeSuit.allocationSize(value)
        }
    }

    override fun write(value: Suit?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeSuit.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeCard: FfiConverterRustBuffer<List<Card>> {
    override fun read(buf: ByteBuffer): List<Card> {
        val len = buf.getInt()
        return List<Card>(len) {
            FfiConverterTypeCard.read(buf)
        }
    }

    override fun allocationSize(value: List<Card>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeCard.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Card>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeCard.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePlacedCard: FfiConverterRustBuffer<List<PlacedCard>> {
    override fun read(buf: ByteBuffer): List<PlacedCard> {
        val len = buf.getInt()
        return List<PlacedCard>(len) {
            FfiConverterTypePlacedCard.read(buf)
        }
    }

    override fun allocationSize(value: List<PlacedCard>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePlacedCard.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PlacedCard>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePlacedCard.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSpread: FfiConverterRustBuffer<List<Spread>> {
    override fun read(buf: ByteBuffer): List<Spread> {
        val len = buf.getInt()
        return List<Spread>(len) {
            FfiConverterTypeSpread.read(buf)
        }
    }

    override fun allocationSize(value: List<Spread>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSpread.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Spread>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSpread.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSpreadSlot: FfiConverterRustBuffer<List<SpreadSlot>> {
    override fun read(buf: ByteBuffer): List<SpreadSlot> {
        val len = buf.getInt()
        return List<SpreadSlot>(len) {
            FfiConverterTypeSpreadSlot.read(buf)
        }
    }

    override fun allocationSize(value: List<SpreadSlot>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSpreadSlot.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SpreadSlot>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSpreadSlot.write(it, buf)
        }
    }
}
        /**
         * UniFFI Exported: Draws a deterministic reading session
         */
    @Throws(TarotException::class) fun `drawReadingSession`(`spreadId`: kotlin.String, `question`: kotlin.String?, `seedHex`: kotlin.String?, `reversalRate`: kotlin.Float): ReadingSession {
            return FfiConverterTypeReadingSession.lift(
    uniffiRustCallWithError(TarotException) { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_draw_reading_session(
        FfiConverterString.lower(`spreadId`),FfiConverterOptionalString.lower(`question`),FfiConverterOptionalString.lower(`seedHex`),FfiConverterFloat.lower(`reversalRate`),_status)
}
    )
    }
    

        /**
         * UniFFI Exported: Generates a 64-character cryptographic CSPRNG seed
         */
    @Throws(TarotException::class) fun `generateRandomSeed`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(TarotException) { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_generate_random_seed(
        _status)
}
    )
    }
    

        /**
         * UniFFI Exported: Retrieves a card archetype definition by card ID (0..77)
         */
    @Throws(TarotException::class) fun `getCardById`(`cardId`: kotlin.UByte): Card {
            return FfiConverterTypeCard.lift(
    uniffiRustCallWithError(TarotException) { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_get_card_by_id(
        FfiConverterUByte.lower(`cardId`),_status)
}
    )
    }
    

        /**
         * UniFFI Exported: Returns static library version string
         */ fun `getTaroturnVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_get_taroturn_version(
        _status)
}
    )
    }
    

        /**
         * UniFFI Exported: Lists all 78 standard Tarot cards
         */ fun `listAllCards`(): List<Card> {
            return FfiConverterSequenceTypeCard.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_list_all_cards(
        _status)
}
    )
    }
    

        /**
         * UniFFI Exported: Lists all built-in canonical spreads
         */ fun `listCanonicalSpreads`(): List<Spread> {
            return FfiConverterSequenceTypeSpread.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_taroturn_core_fn_func_list_canonical_spreads(
        _status)
}
    )
    }
    


