# Script to generate crates/taroturn-core/src/card.rs with zero-allocation static table
import os

MAJOR_CARDS = [
    (0, "major_00_fool", "Air", "The Fool", "愚者", "Uranus / Air", "Aleph",
     ["New Beginnings", "Innocence", "Spontaneity", "Free Spirit"],
     ["Recklessness", "Risk-taking", "Inconsideration", "Naivety"],
     "Spontaneous romantic encounter, open heart",
     "Hesitation to commit or reckless romantic choices",
     "New career venture, entrepreneurial leap of faith",
     "Impulsive career move without safety net",
     "Embarking on a profound spiritual quest",
     "Blind spiritual following or fear of the unknown",
     "Denial of earthly consequences in pursuit of freedom"),
    (1, "major_01_magician", "Air", "The Magician", "魔术师", "Mercury", "Beth",
     ["Manifestation", "Resourcefulness", "Power", "Inspired Action"],
     ["Illusion", "Manipulation", "Untapped Potential", "Wasted Talent"],
     "Clear communication, attraction, conscious relationship building",
     "Deception, hidden intentions, manipulation in romance",
     "Mastery of skills, project launch, resource alignment",
     "Misplaced efforts, trickery, stagnation in career",
     "Aligning will with universal intention",
     "Spiritual arrogance or misuse of inner energy",
     "Over-reliance on cleverness at the expense of genuine depth"),
    (2, "major_02_high_priestess", "Water", "The High Priestess", "女祭司", "Moon", "Gimel",
     ["Intuition", "Sacred Knowledge", "Divine Feminine", "Subconscious"],
     ["Secrets", "Disconnected from Intuition", "Repression", "Silence"],
     "Deep soul connection, intuitive harmony, patience in romance",
     "Emotional distance, unexpressed feelings, hidden secrets",
     "Quiet observation, research, strategic insight before action",
     "Superficial work environment, gossip, ignoring gut instincts",
     "Direct contact with inner wisdom and mystical realms",
     "Spiritual confusion, dogmatic beliefs blocking true sight",
     "Withdrawal from worldly connection out of fear of vulnerability"),
    (3, "major_03_empress", "Earth", "The Empress", "女皇", "Venus", "Daleth",
     ["Fertility", "Abundance", "Nurturing", "Sensuality", "Creativity"],
     ["Creative Block", "Dependence", "Overbearing", "Depletion"],
     "Warm unconditional love, sensuality, growing commitment",
     "Codependency, smothering love, emotional depletion",
     "Fruitful creative projects, prosperous business growth",
     "Creative burnout, stagnation, financial neglect",
     "Embodiment of earthly beauty and maternal grace",
     "Neglect of physical vessel or creative spirit",
     "Overindulgence in material comfort avoiding necessary discipline"),
    (4, "major_04_emperor", "Fire", "The Emperor", "皇帝", "Aries", "He",
     ["Authority", "Structure", "Stability", "Fatherhood", "Leadership"],
     ["Tyranny", "Rigidity", "Lack of Discipline", "Loss of Control"],
     "Solid commitment, clear boundaries, reliable partnership",
     "Controlling behavior, emotional coldness, power struggles",
     "Executive leadership, structural order, clear strategy",
     "Micromanagement, chaos, ineffective authority",
     "Establishing structured spiritual practice and discipline",
     "Rigid dogma stifling spiritual spontaneity",
     "Fear of chaos driving obsessive control"),
    (5, "major_05_hierophant", "Earth", "The Hierophant", "教皇", "Taurus", "Vav",
     ["Spiritual Wisdom", "Tradition", "Institutions", "Mentorship"],
     ["Personal Beliefs", "Rebellion", "Unconventional", "Dogma"],
     "Traditional relationship values, shared ethics, marriage",
     "Unconventional relationship, questioning social norms",
     "Established corporate structure, institutional mentorship",
     "Bureaucratic friction, breaking out of orthodox patterns",
     "Study of sacred lineages and traditional teachings",
     "Formulating individualized spiritual philosophy",
     "Clinging to outer forms while losing inner esoteric essence"),
    (6, "major_06_lovers", "Air", "The Lovers", "恋人", "Gemini", "Zayin",
     ["Love", "Harmony", "Relationships", "Values Alignment", "Choices"],
     ["Disharmony", "Imbalance", "Misaligned Values", "Conflict"],
     "Deep soulmate connection, mutual vulnerability, union",
     "Values dissonance, communication breakdown, trust issues",
     "Fruitful partnership, ethical decision making in business",
     "Internal conflict between passion and practical duty",
     "Integration of dualistic aspects within the psyche",
     "Internal moral dilemma or divided loyalty",
     "Seeking external completion rather than inner wholeness"),
    (7, "major_07_chariot", "Water", "The Chariot", "战车", "Cancer", "Cheth",
     ["Control", "Willpower", "Success", "Determination", "Focus"],
     ["Lack of Control", "Aggression", "Directionless", "Obstacles"],
     "Courageous pursuit in romance, overcoming relationship hurdles",
     "Impatience or forceful pressure straining romantic bond",
     "Triumph over business competition, milestone conquest",
     "Power struggles, burnout, derailment of key deliverables",
     "Harnessing opposing psychic impulses toward unified goal",
     "Spiritual dispersion, loss of center under external storms",
     "Suppressing authentic emotion to maintain an armor of control"),
    (8, "major_08_strength", "Fire", "Strength", "力量", "Leo", "Teth",
     ["Courage", "Persuasion", "Compassion", "Inner Strength", "Patience"],
     ["Self-Doubt", "Raw Emotion", "Weakness", "Inner Turmoil"],
     "Loving patience, gentle taming of emotional tempests",
     "Insecurity, vulnerability fear, reactive explosive anger",
     "Quiet resilience in challenging corporate negotiations",
     "Confidence deficit, yielding to undue intimidation",
     "Compassionate mastery over instinctual animal nature",
     "Struggling with shadow self or spiritual exhaustion",
     "Mistaking aggressive dominance for genuine inner fortitude"),
    (9, "major_09_hermit", "Earth", "The Hermit", "隐士", "Virgo", "Yod",
     ["Soul Searching", "Introspection", "Solitude", "Inner Guidance"],
     ["Isolation", "Loneliness", "Withdrawal", "Paranoia"],
     "Solitary contemplation, finding wholeness before union",
     "Emotional isolation, shutting partner out defensively",
     "Career recalibration, autonomous specialist research",
     "Professional detachment, alienation from team dynamics",
     "Guiding lantern on the path of self-illumination",
     "Spiritual arrogance or fear of worldly re-engagement",
     "Using intellectual solitude as an escape from intimacy"),
    (10, "major_10_wheel_of_fortune", "Fire", "Wheel of Fortune", "命运之轮", "Jupiter", "Kaph",
     ["Good Luck", "Karma", "Life Cycles", "Destiny", "Turning Point"],
     ["Bad Luck", "Resistance to Change", "Breaking Cycles", "Disruption"],
     "Fateful meeting, cyclical evolution of emotional stages",
     "External circumstances disrupting romantic equilibrium",
     "Lucky opportunity, market inflection point, sudden breakthrough",
     "Unexpected setback, cyclical downturn, timing mismatch",
     "Understanding the cosmic dance of karma and impermanence",
     "Fatalistic helplessness or resisting inevitable evolution",
     "Clinging to momentary peaks while fearing inescapable valleys"),
    (11, "major_11_justice", "Air", "Justice", "正义", "Libra", "Lamed",
     ["Justice", "Fairness", "Truth", "Cause and Effect", "Law"],
     ["Unfairness", "Lack of Accountability", "Dishonesty", "Bias"],
     "Honest communication, equal partnership, balanced give-and-take",
     "One-sided emotional ledger, unresolved disputes, dishonesty",
     "Fair contracts, legal resolution, merit-based recognition",
     "Contractual disputes, unfair treatment, evasive accountability",
     "Universal karmic alignment and radical self-honesty",
     "Self-deception, projection of blame onto others",
     "Cold legalistic judgment devoid of compassionate understanding"),
    (12, "major_12_hanged_man", "Water", "The Hanged Man", "倒吊人", "Neptune / Water", "Mem",
     ["Surrender", "New Perspective", "Letting Go", "Pause", "Sacrifice"],
     ["Delays", "Resistance", "Stalling", "Martyrdom"],
     "Surrendering ego demands, seeing partner from fresh angle",
     "Playing the martyr, unnecessary sacrifice causing resentment",
     "Strategic pause, incubating ideas, unconventional solution",
     "Aimless stalling, procrastination, involuntary standstill",
     "Spiritual enlightenment gained through ego surrender",
     "Futile resistance against necessary spiritual shedding",
     "Feigning spiritual detachment while nursing passive aggression"),
    (13, "major_13_death", "Water", "Death", "死神", "Scorpio", "Nun",
     ["Endings", "Transformation", "Transition", "New Beginnings"],
     ["Resistance to Change", "Stagnation", "Decay", "Fear of Ending"],
     "Closure of outdated relational dynamics, transformative renewal",
     "Clinging to a deceased dynamic out of fear of solitude",
     "Career metamorphosis, conclusion of a project phase, rebranding",
     "Remaining trapped in an unviable professional dead-end",
     "Psychic death of the obsolete self paving way for rebirth",
     "Dread of mortality and spiritual transformation",
     "Denial of natural decay, hindering emergent vitality"),
    (14, "major_14_temperance", "Fire", "Temperance", "节制", "Sagittarius", "Samekh",
     ["Balance", "Moderation", "Patience", "Purpose", "Alchemy"],
     ["Imbalance", "Excess", "Self-Healing", "Re-alignment"],
     "Harmonious blending of differences, gentle emotional pacing",
     "Extremes of emotion, impatience, relational turbulence",
     "Collaborative synergy, measured workload, strategic patience",
     "Burnout, reckless overextension, conflicting team factions",
     "Alchemical synthesis of inner polarities into spiritual gold",
     "Spiritual dissonance, fragmented inner energies",
     "Compromising core truth under guise of superficial peace"),
    (15, "major_15_devil", "Earth", "The Devil", "恶魔", "Capricorn", "Ayin",
     ["Shadow Self", "Attachment", "Addiction", "Restriction", "Materialism"],
     ["Release", "Freedom", "Restoring Control", "Overcoming Addiction"],
     "Intense magnetic obsession, toxic codependency, lustful bond",
     "Breaking free from relational shackles, recognizing illusions",
     "Golden handcuffs, burnout, unfulfilling corporate servitude",
     "Reclaiming professional autonomy, divesting from toxic work",
     "Confronting repressed shadow archetypes without fear",
     "Liberation from dogmatic spiritual bondage",
     "Willful blindness to self-imposed psychic chains"),
    (16, "major_16_tower", "Fire", "The Tower", "高塔", "Mars", "Pe",
     ["Sudden Change", "Upheaval", "Chaos", "Revelation", "Awakening"],
     ["Personal Transformation", "Fear of Change", "Averting Disaster"],
     "Shocking revelation, sudden breakdown of relational facade",
     "Internal emotional quake, delaying inevitable disclosure",
     "Corporate restructuring, unexpected termination, paradigm shift",
     "Narrowly surviving a structural crisis, rebuilding from rubble",
     "Lightning bolt of divine truth shattering ego constructs",
     "Spiritual crisis leading to authentic foundation",
     "Building towering defense mechanisms upon rotten foundations"),
    (17, "major_17_star", "Air", "The Star", "星星", "Aquarius", "Tzaddi",
     ["Hope", "Faith", "Purpose", "Renewal", "Spirituality", "Inspiration"],
     ["Lack of Faith", "Despair", "Self-Trust", "Disconnection"],
     "Healing after heartbreak, tranquil optimism, genuine openness",
     "Disillusionment, pessimism, closing off to romantic hope",
     "Visionary career inspiration, long-term brand elevation",
     "Creative drought, imposter syndrome, losing faith in goals",
     "Direct communion with cosmic grace and spiritual serenity",
     "Spiritual fatigue, feeling abandoned by the divine",
     "Passive wishful daydreaming without grounded physical execution"),
    (18, "major_18_moon", "Water", "The Moon", "月亮", "Pisces", "Qoph",
     ["Illusion", "Fear", "Anxiety", "Subconscious", "Intuition"],
     ["Release of Fear", "Unveiled Secrets", "Clarity", "Overcoming"],
     "Misunderstandings, projected insecurities, subconscious fears",
     "Lifting the veil of deception, clarity emerging in romance",
     "Ambiguous workplace dynamics, hidden agendas, uncertain terms",
     "Truth exposed, navigating through corporate fog to clarity",
     "Night journey through the mythic realm of the shadow",
     "Escaping terrifying psychic nightmares into conscious dawn",
     "Mistaking neurotic anxiety for genuine intuitive insight"),
    (19, "major_19_sun", "Fire", "The Sun", "太阳", "Sun", "Resh",
     ["Positivity", "Fun", "Warmth", "Success", "Vitality", "Joy"],
     ["Inner Child", "Feeling Down", "Overly Optimistic", "Clouded"],
     "Radiant joy, mutual adoration, vibrant shared happiness",
     "Minor temporary dampening of joy, needing inner warmth",
     "Triumphant business success, public acclaim, creative vitality",
     "Unrealistic expectations, superficial optimism needing realism",
     "Solar consciousness, radiant vitality and integrated wholeness",
     "Reconnecting with wounded inner child to restore light",
     "Blinding oneself to genuine nuance with toxic positivity"),
    (20, "major_20_judgement", "Fire", "Judgement", "审判", "Pluto / Fire", "Shin",
     ["Judgement", "Rebirth", "Inner Calling", "Absolution", "Awakening"],
     ["Self-Doubt", "Harsh Self-Criticism", "Ignoring the Call"],
     "Awakening to true relationship purpose, forgiveness, renewal",
     "Holding grudges, paralyzing guilt, refusing to forgive",
     "Vocation awakening, major career evaluation, taking the leap",
     "Second-guessing destiny, fear of being judged by peers",
     "Hearing the trumpet of the soul and answering higher calling",
     "Repressing spiritual awakening due to fear of transformation",
     "Cruel self-condemnation masquerading as spiritual vigilance"),
    (21, "major_21_world", "Earth", "The World", "世界", "Saturn", "Tav",
     ["Completion", "Integration", "Accomplishment", "Travel", "Fulfillment"],
     ["Seeking Closure", "Shortcuts", "Delays", "Incompletion"],
     "Harmonious culmination, holistic love, soul-level fulfillment",
     "Lingering unfinished business, longing for elusive closure",
     "Grand project completion, international acclaim, ultimate milestone",
     "Almost at finish line but taking dangerous shortcuts",
     "Attaining cosmic consciousness and wholeness in the universe",
     "Stuck at threshold of spiritual mastery before final surrender",
     "Fear of completing a major life chapter because of the unknown void after"),
]

MINOR_DATA = [
    # Wands (Fire)
    ("Wands", "wands", "Fire", [
        ("Ace", "01_ace", "Ace of Wands", "权杖一", "Root of the Powers of Fire", "Kether in Atziluth",
         ["Inspiration", "New Passion", "Creative Spark", "Courage"],
         ["Delays", "Lack of Motivation", "Creative Block", "Hesitation"],
         "Passionate new spark, magnetic romantic attraction", "Fading enthusiasm or fear of initiating romance",
         "Breakthrough venture, bold entrepreneurial initiative", "Stalled initiative, lack of follow-through",
         "Direct infusion of creative primal spiritual fire", "Creative spiritual drought, scattered energy",
         "Impulsive obsession without grounded emotional maturity"),
        ("Two", "02_two", "Two of Wands", "权杖二", "Mars in Aries (0°-10° / Dominion)", "Chokmah in Atziluth",
         ["Planning", "Future Vision", "Progress", "Decisions", "Discovery"],
         ["Fear of Unknown", "Lack of Planning", "Playing it Safe", "Overanalysis"],
         "Envisioning shared future, planning joint horizons", "Reluctance to commit to long-term relational vision",
         "Strategic expansion, overseas markets, long-term roadmap", "Hesitation to step outside comfortable territory",
         "Broadening spiritual horizons, stepping beyond comfort zone", "Spiritual inertia, clinging to familiar dogmas",
         "Arrogant empire-building neglecting immediate emotional bonds"),
        ("Three", "03_three", "Three of Wands", "权杖三", "Sun in Aries (10°-20° / Established Strength)", "Binah in Atziluth",
         ["Expansion", "Foresight", "Overseas Opportunities", "Confidence"],
         ["Obstacles", "Delays in Returns", "Frustration", "Disappointment"],
         "Long-distance connection, mutual exploration, shared growth", "Patience tested in relationship timing",
         "Ventures yielding returns, global partnership, scaling up", "Supply chain friction, delayed milestones",
         "Watching inner spiritual seeds manifest in physical world", "Doubt during necessary gestation periods",
         "Restless desire for the next horizon discounting present achievements"),
        ("Four", "04_four", "Four of Wands", "权杖四", "Venus in Aries (20°-30° / Perfected Work)", "Chesed in Atziluth",
         ["Celebration", "Harmony", "Homecoming", "Community", "Milestone"],
         ["Personal Celebration", "Domestic Tension", "Transient Peace", "Exclusion"],
         "Engagement, joyous wedding, solid domestic harmony", "Family friction, feeling uninvited or tense at home",
         "Project milestone celebration, stable supportive work culture", "Internal team conflict disrupting harmony",
         "Sacred sanctuary, celebrating community spiritual harmony", "Over-attachment to external rituals",
         "Superficial peace masking unresolved structural issues"),
        ("Five", "05_five", "Five of Wands", "权杖五", "Saturn in Leo (0°-10° / Strife)", "Geburah in Atziluth",
         ["Conflict", "Competition", "Disagreements", "Diversity of Ideas"],
         ["Avoiding Conflict", "Internal Conflict", "Resolution", "Harmony"],
         "Ego clashes, petty bickering, competitive tension", "Repressing grievances or resolving dispute peacefully",
         "Market competition, brainstorming friction, organizational rivalry", "Passive aggressive corporate politics",
         "Spiritual tests through external friction and challenges", "Internal spiritual discord and divided will",
         "Wasting vital creative energy on pointless dominance games"),
        ("Six", "06_six", "Six of Wands", "权杖六", "Jupiter in Leo (10°-20° / Victory)", "Tiphareth in Atziluth",
         ["Success", "Public Recognition", "Progress", "Self-Confidence"],
         ["Egotism", "Fall from Grace", "Lack of Recognition", "Disgrace"],
         "Admired partner, celebrated relationship, mutual pride", "Seeking external validation over authentic intimacy",
         "Triumphant delivery, industry award, leadership acclaim", "Imposter syndrome, delayed credit, hubris",
         "Radiant solar self-actualization and moral victory", "Spiritual pride and craving for followers",
         "Narcissistic thirst for applause undermining core humility"),
        ("Seven", "07_seven", "Seven of Wands", "权杖七", "Mars in Leo (20°-30° / Valour)", "Netzach in Atziluth",
         ["Perseverance", "Defending Position", "Courage", "Standing Ground"],
         ["Giving In", "Overwhelmed", "Exhaustion", "Compromise"],
         "Defending love against outside critics, unwavering loyalty", "Feeling besieged by external relationship pressure",
         "Defending market leadership, holding ground under scrutiny", "Overwhelmed by competitors, burnout",
         "Courageous defense of spiritual integrity and personal truth", "Yielding core beliefs to crowd consensus",
         "Paranoid defensiveness mistaking helpful feedback for attack"),
        ("Eight", "08_eight", "Eight of Wands", "权杖八", "Mercury in Sagittarius (0°-10° / Swiftness)", "Hod in Atziluth",
         ["Speed", "Rapid Action", "Movement", "Quick Communication", "Travel"],
         ["Delays", "Frustration", "Hastiness", "Panic", "Misunderstandings"],
         "Whirlwind romance, rapid passionate text exchange", "Impulsive romantic declarations or communication delay",
         "Fast-track project execution, rapid product launch, travel", "Rushing without QA, chaotic miscommunication",
         "Sudden acceleration of spiritual awakening and synchronicity", "Scattered psychic energy and mental frenzy",
         "Speed for speed's sake without clear intentional destination"),
        ("Nine", "09_nine", "Nine of Wands", "权杖九", "Moon in Sagittarius (10°-20° / Great Strength)", "Yesod in Atziluth",
         ["Resilience", "Grit", "Last Line of Defense", "Persistence"],
         ["Exhaustion", "Giving Up", "Defensiveness", "Paranoia"],
         "Guarded heart from past trauma, testing partner's loyalty", "Vulnerability block, unyielding emotional fortress",
         "Final sprint before delivery, battle-tested endurance", "Chronic burnout, near surrender at final hurdle",
         "Guarding the spiritual flame through dark night of soul", "Spiritual fatigue, hypervigilance",
         "Chronic hyper-vigilance perpetuating imaginary enemies"),
        ("Ten", "10_ten", "Ten of Wands", "权杖十", "Saturn in Sagittarius (20°-30° / Oppression)", "Malkuth in Atziluth",
         ["Burden", "Extra Responsibility", "Hard Work", "Stress", "Overextension"],
         ["Delegating", "Releasing Burden", "Burnout", "Collapse"],
         "Carrying emotional load alone, weighed down by relational duty", "Sharing burdens, delegating emotional labor",
         "Overloaded with deliverables, single point of failure", "Severe burnout, refusing to delegate, collapse",
         "Carrying worldly karmic burdens toward spiritual liberation", "Spiritual martyrdom and savior complex",
         "Masochistic workaholism used to avoid inner emptiness"),
        ("Page", "11_page", "Page of Wands", "权杖侍从", "Earth of Fire / Princess of Flame", "Malkuth in Atziluth",
         ["Enthusiasm", "Exploration", "Discovery", "Free Spirit", "New Ideas"],
         ["Setbacks", "Lack of Goals", "Procrastination", "Immaturity"],
         "Playful flirting, exciting romantic messages, fresh start", "Flighty commitment, juvenile romantic games",
         "Junior spark of innovation, eager research, exploring ideas", "Lack of follow-through, impulsive career shifts",
         "Youthful enthusiasm for spiritual discovery and occult studies", "Dabbling in spiritual trends without depth",
         "Addiction to initial novelty abandoning mastery when discipline is needed"),
        ("Knight", "12_knight", "Knight of Wands", "权杖骑士", "Fire of Fire / Lord of Flame", "Tiphareth in Atziluth",
         ["Energy", "Passion", "Adventure", "Impulsiveness", "Action"],
         ["Anger", "Impatience", "Recklessness", "Volatile"],
         "Fiery romantic pursuit, passionate whirlwind, charismatic charm", "Hot-and-cold behavior, ghosting, impatience",
         "Aggressive market disruption, bold pitches, swift action", "Reckless overpromising, volatile team friction",
         "Passionate spiritual crusade and radiant devotion", "Dogmatic fanaticism, spiritual burnout",
         "Chasing adrenaline surges mistaking restlessness for purpose"),
        ("Queen", "13_queen", "Queen of Wands", "权杖王后", "Water of Fire / Queen of Thrones of Flame", "Briah in Atziluth",
         ["Courage", "Confidence", "Independence", "Social Grace", "Warmth"],
         ["Self-Doubt", "Jealousy", "Demanding", "Insecurity"],
         "Radiant magnetic confidence, charismatic warm partner", "Demanding spotlight, jealous insecurity",
         "Inspirational executive leadership, vibrant team morale", "Temperamental outbursts, micromanagement",
         "Embodied spiritual magnetism, living as radiant beacon", "Manipulative charisma, spiritual vanity",
         "Dominating others under guise of enthusiastic cheerleading"),
        ("King", "14_king", "King of Wands", "权杖国王", "Air of Fire / Prince of Chariot of Fire", "Chokmah in Atziluth",
         ["Visionary Leadership", "Honor", "Overcoming Challenges", "Charisma"],
         ["Impulsiveness", "Ruthlessness", "High Expectations", "Tyranny"],
         "Mature passionate commitment, protective inspiring leader", "Overbearing dominance, impatience with partner",
         "C-level visionary, inspiring corporate scaling, decisive strategy", "Autocratic leadership, unrealistic demands",
         "Mastery of creative spiritual fire and ethical manifestation", "Spiritual arrogance, demanding total obedience",
         "Burning bridges in pursuit of grand ungrounded visions"),
    ]),

    # Cups (Water)
    ("Cups", "cups", "Water", [
        ("Ace", "01_ace", "Ace of Cups", "圣杯一", "Root of the Powers of Water", "Kether in Briah",
         ["Love", "New Feelings", "Intuition", "Compassion", "Creativity"],
         ["Self-Love", "Blocked Intuition", "Emotional Drain", "Vulnerability"],
         "Overflowing romantic love, deep heart-opening, soul resonance", "Unexpressed affection, fear of intimacy",
         "Fulfilling vocation, compassionate creative collaboration", "Creative block, professional dissatisfaction",
         "Direct infusion of divine unconditional love and grace", "Emotional spiritual blockage, feeling numb",
         "Unbounded emotional indulgence drowning rational discernment"),
        ("Two", "02_two", "Two of Cups", "圣杯二", "Venus in Cancer (0°-10° / Love)", "Chokmah in Briah",
         ["Unified Love", "Partnership", "Mutual Attraction", "Harmony"],
         ["Breakup", "Imbalance", "Misaligned Values", "Distrust"],
         "Soulmate connection, equal vulnerability, harmonious union", "One-sided attraction, communication breakdown",
         "Synergistic co-founder partnership, mutual business trust", "Contractual discord, broken partnership",
         "Sacred spiritual marriage (Hieros Gamos) within the soul", "Inner division between head and heart",
         "Codependent fusion sacrificing personal autonomy for peace"),
        ("Three", "03_three", "Three of Cups", "圣杯三", "Mercury in Cancer (10°-20° / Abundance)", "Binah in Briah",
         ["Celebration", "Friendship", "Sisterhood", "Community", "Gathering"],
         ["Gossip", "Isolation", "Overindulgence", "Third-Party Friction"],
         "Joyous social dating, shared circle of friends, celebration", "Third-party interference, gossip harming intimacy",
         "Team milestone party, collaborative synergy, festive launch", "Office cliques, gossiping, unproductive meetings",
         "Joyful community communion and shared spiritual circle", "Spiritual elitism and superficial groupthink",
         "Using superficial party euphoria to numb underlying melancholy"),
        ("Four", "04_four", "Four of Cups", "圣杯四", "Moon in Cancer (20°-30° / Luxury)", "Chesed in Briah",
         ["Apathy", "Contemplation", "Disconnection", "Melancholy"],
         ["Clarity", "Acceptance", "Seizing Opportunity", "Awakening"],
         "Emotional boredom, taking partner for granted, withdrawal", "Recognizing love offered, opening up to connection",
         "Career stagnation, uninspired by current offers, apathy", "Seizing overlooked project opportunity, renewed drive",
         "Meditation on inner emptiness, quiet contemplation", "Refusing spiritual grace out of stubborn cynicism",
         "Chronic dissatisfaction romanticizing unattainable illusions"),
        ("Five", "05_five", "Five of Cups", "圣杯五", "Mars in Scorpio (0°-10° / Loss in Pleasure)", "Geburah in Briah",
         ["Grief", "Loss", "Regret", "Disappointment", "Mourning"],
         ["Acceptance", "Moving On", "Finding Peace", "Forgiveness"],
         "Heartbreak, grieving lost love, lingering regret", "Turning around to see remaining love, forgiveness",
         "Failed deal, project setback, mourning sunk costs", "Pivoting strategy, salvaging remaining assets",
         "Grief as an initiation into deeper spiritual empathy", "Trapped in perpetual victimhood and sorrow",
         "Obsessive mourning over spilled cups ignoring standing reserves"),
        ("Six", "06_six", "Six of Cups", "圣杯六", "Sun in Scorpio (10°-20° / Pleasure)", "Tiphareth in Briah",
         ["Nostalgia", "Childhood Memories", "Innocence", "Reunion"],
         ["Stuck in Past", "Unrealistic Idealism", "Moving Forward"],
         "Sweet nostalgic romance, childhood sweetheart, gentle warmth", "Idealizing ex-partner, clinging to obsolete past",
         "Revisiting past clients, family business, legacy project", "Reluctance to adopt modern methods, outmoded tech",
         "Reconnecting with innocent pure inner child", "Escaping adult spiritual responsibility into childhood fantasy",
         "Trapping current relationships in golden nostalgic cages"),
        ("Seven", "07_seven", "Seven of Cups", "圣杯七", "Venus in Scorpio (20°-30° / Illusionary Success)", "Netzach in Briah",
         ["Choices", "Fantasy", "Illusion", "Wishful Thinking", "Options"],
         ["Clarity", "Decisiveness", "Reality Check", "Sober Choices"],
         "Daydreaming multiple romantic prospects, fantasy vs reality", "Sober choice, cutting through romantic illusions",
         "Too many project ideas, scattered strategy, paralysis by analysis", "Prioritizing viable MVP, realistic execution",
         "Exploring astral realms and multifaceted mythic visions", "Lost in spiritual glamour and psychic daydreaming",
         "Chasing shiny mirages to avoid grounded hard work"),
        ("Eight", "08_eight", "Eight of Cups", "圣杯八", "Saturn in Pisces (0°-10° / Abandoned Success)", "Hod in Briah",
         ["Walking Away", "Disillusionment", "Leaving Behind", "Searching for Truth"],
         ["Aimless Drifting", "Fear of Moving On", "Clinging to Dead Ends"],
         "Walking away from unfulfilling relationship, seeking deeper truth", "Staying in hollow relationship out of fear",
         "Leaving comfortable corporate job to pursue authentic vocation", "Drifting aimlessly without career direction",
         "The spiritual hero's quest, nocturnal departure toward the peaks", "Fear of leaving material security behind",
         "Chronic dissatisfaction disguised as spiritual seeking"),
        ("Nine", "09_nine", "Nine of Cups", "圣杯九", "Jupiter in Pisces (10°-20° / Material Happiness)", "Yesod in Briah",
         ["Contentment", "Satisfaction", "Wishes Fulfilled", "Gratitude"],
         ["Greed", "Smugness", "Superficiality", "Dissatisfaction"],
         "Emotional bliss, dream partner, deep romantic fulfillment", "Self-satisfied complacency, superficial pleasure",
         "Lucrative milestone, dream job achieved, proud satisfaction", "Smug entitlement, resting on past laurels",
         "Inner spiritual peace and emotional self-sufficiency", "Hedonistic self-indulgence masquerading as enlightenment",
         "Smug isolation mistaking material comfort for soul growth"),
        ("Ten", "10_ten", "Ten of Cups", "圣杯十", "Mars in Pisces (20°-30° / Perfected Success)", "Malkuth in Briah",
         ["Divine Love", "Family Harmony", "Lasting Happiness", "Alignment"],
         ["Domestic Discord", "Shattered Dreams", "Strained Relations"],
         "Lasting marriage, family bliss, complete emotional harmony", "Domestic tension, facade of happy family",
         "Wholesome corporate culture, aligned values, shared prosperity", "Corporate culture clash, toxic work environment",
         "Living in harmony with universal cosmic love", "Spiritual disillusionment within community",
         "Imposing dogmatic happily-ever-after templates on messy human truth"),
        ("Page", "11_page", "Page of Cups", "圣杯侍从", "Earth of Water / Princess of the Waters", "Malkuth in Briah",
         ["Creative Intuition", "Gentle Curiosity", "Intuitive Messages", "Sensitivity"],
         ["Emotional Immaturity", "Insecurity", "Overly Sensitive", "Vulnerability"],
         "Sweet romantic confession, poetic affection, tender message", "Emotional mood swings, childish insecurity",
         "Creative inspiration, artistic breakthrough, fresh perspectives", "Unrealistic proposals, feeling easily hurt by feedback",
         "Gentle psychic opening and receptive intuitive whispers", "Psychic gullibility, emotional escapism",
         "Playing the fragile wounded poet to manipulate care from others"),
        ("Knight", "12_knight", "Knight of Cups", "圣杯骑士", "Fire of Water / Lord of Waves and Waters", "Tiphareth in Briah",
         ["Romance", "Charm", "Idealism", "Following Heart", "Diplomacy"],
         ["Unrealistic Expectations", "Moodiness", "Deception", "Heartbreak"],
         "Romantic courtship, chivalrous partner, poetic declarations", "Love-bombing followed by withdrawal, illusion",
         "Diplomatic negotiations, creative pitch, visionary ambassador", "All style no substance, unreliable deadlines",
         "Devoted spiritual seeker pursuing the Holy Grail", "Chasing spiritual romance without grounded discipline",
         "Seducing others with idealistic promises one cannot sustain"),
        ("Queen", "13_queen", "Queen of Cups", "圣杯王后", "Water of Water / Queen of Thrones of Waters", "Briah in Briah",
         ["Empathy", "Compassion", "Intuitive Healing", "Emotional Depth"],
         ["Codependency", "Martyrdom", "Emotional Manipulation", "Moodiness"],
         "Deep empathetic love, psychic connection, safe emotional haven", "Smothering codependency, emotional martyrdom",
         "Empathetic leadership, intuitive client resonance, mentorship", "Allowing emotions to cloud executive judgment",
         "High intuitive mastery, direct channel of divine compassion", "Drowning in psychic projections and emotional swamp",
         "Absorbing everyone else's trauma to avoid one's own boundary setting"),
        ("King", "14_king", "King of Cups", "圣杯国王", "Air of Water / Prince of Chariot of Waters", "Chokmah in Briah",
         ["Emotional Balance", "Compassion", "Wisdom", "Diplomacy", "Counsel"],
         ["Emotional Volatility", "Manipulation", "Coldness", "Withholding"],
         "Emotionally mature partner, calm anchor during relational storms", "Passive-aggressive withholding, manipulative calm",
         "Wise senior executive, trusted counselor, calm crisis management", "Suppressed corporate anger, covert manipulation",
         "Mastery over emotional tides with serene spiritual wisdom", "Spiritual detachment turned into emotional numbness",
         "Using calm intellectual superiority to suppress raw authentic feelings"),
    ]),

    # Swords (Air)
    ("Swords", "swords", "Air", [
        ("Ace", "01_ace", "Ace of Swords", "宝剑一", "Root of the Powers of Air", "Kether in Yetzirah",
         ["Clarity", "Raw Truth", "Breakthrough", "Sharp Intellect", "Justice"],
         ["Confusion", "Brutality", "Misinformation", "Hostility"],
         "Honest breakthrough conversation, cutting through ambiguity", "Brutal harsh words, painful misunderstanding",
         "Strategic clarity, sharp technical solution, decisive audit", "Miscalculated strategy, analysis paralysis",
         "Sword of discriminating wisdom piercing veil of illusion", "Using intellect to rationalize spiritual ego",
         "Wielding brutal honesty as a weapon to wound rather than heal"),
        ("Two", "02_two", "Two of Swords", "宝剑二", "Moon in Libra (0°-10° / Peace Restored)", "Chokmah in Yetzirah",
         ["Stalemate", "Difficult Choice", "Truce", "Blindspot", "Avoidance"],
         ["Indecision", "Information Overload", "Conflict", "Exposure"],
         "Emotional standoff, avoiding tough decision, temporary truce", "Forced revelation, emotional impasse breaking",
         "Corporate deadlock, balancing trade-offs, defensive pause", "Indecisive leadership stalling project momentum",
         "Quiet mental balance before inner wisdom reveals path", "Willful blindness to obvious spiritual truths",
         "Wearing blindfold of intellectual neutrality to evade moral choice"),
        ("Three", "03_three", "Three of Swords", "宝剑三", "Saturn in Libra (10°-20° / Sorrow)", "Binah in Yetzirah",
         ["Heartbreak", "Painful Truth", "Grief", "Betrayal", "Surgical Clarity"],
         ["Recovery", "Forgiveness", "Releasing Pain", "Repression"],
         "Painful heartbreak, shattered illusions, necessary grief", "Healing from past betrayal, releasing bitterness",
         "Severed contract, harsh audit findings, restructuring pain", "Rebuilding from business setback, forgiveness",
         "The piercing of ego illusions leading to compassionate heart", "Refusing to acknowledge profound inner grief",
         "Obsessively picking at old psychic wounds to justify bitterness"),
        ("Four", "04_four", "Four of Swords", "宝剑四", "Jupiter in Libra (20°-30° / Rest from Strife)", "Chesed in Yetzirah",
         ["Rest", "Recovery", "Meditation", "Sanctuary", "Contemplation"],
         ["Exhaustion", "Burnout", "Forced Rest", "Stagnation"],
         "Taking space in relationship, emotional recovery, quiet sanctuary", "Isolation out of fear, emotional coldness",
         "Strategic pause, sabbatical, recharging before major release", "Severe burnout forcing medical leave",
         "Silent meditation, inner temple sanctuary, mental stillness", "Mental restlessness disturbing spiritual retreat",
         "Using spiritual retreat as permanent hiding place from life"),
        ("Five", "05_five", "Five of Swords", "宝剑五", "Venus in Aquarius (0°-10° / Defeat)", "Geburah in Yetzirah",
         ["Conflict", "Pyrrhic Victory", "Hostility", "Self-Interest"],
         ["Reconciliation", "Compromise", "Past Resentment", "Humility"],
         "Winning argument but losing relationship, toxic ego battles", "Reconciling after dispute, laying down weapons",
         "Cutthroat corporate politics, hollow victory, alienated peers", "Forgiving business rivals, rebuilding trust",
         "Recognizing futility of spiritual ego dominance games", "Persistent resentment and gloating over adversaries",
         "Needing to win every minor battle at cost of entire alliance"),
        ("Six", "06_six", "Six of Swords", "宝剑六", "Mercury in Aquarius (10°-20° / Earned Success)", "Tiphareth in Yetzirah",
         ["Transition", "Moving Forward", "Leaving Turmoil", "Recovery"],
         ["Emotional Baggage", "Turbulence", "Reluctance to Move"],
         "Transitioning to calmer waters together, healing after storm", "Carrying heavy baggage into new relationship",
         "Migrating legacy codebase, relocation, emerging from crisis", "Stuck in problematic legacy architecture",
         "Mental voyage across astral waters toward spiritual peace", "Refusing guidance across difficult inner transitions",
         "Carrying unresolved cognitive dissonance into every new haven"),
        ("Seven", "07_seven", "Seven of Swords", "宝剑七", "Moon in Aquarius (20°-30° / Unstable Effort)", "Netzach in Yetzirah",
         ["Strategy", "Stealth", "Resourcefulness", "Deception", "Evasion"],
         ["Confession", "Imposter Syndrome", "Getting Caught", "Sincerity"],
         "Hidden agendas, evasive behavior, sneaky communication", "Coming clean, honest confession, rebuilding trust",
         "Tactical stealth, protecting IP, unconventional strategy", "Unethical shortcuts, fraud, getting caught",
         "Testing subtle discernment against spiritual illusions", "Deceiving oneself regarding spiritual attainment",
         "Rationalizing deceit as clever strategy"),
        ("Eight", "08_eight", "Eight of Swords", "宝剑八", "Jupiter in Gemini (0°-10° / Shortened Force)", "Hod in Yetzirah",
         ["Self-Imposed Restriction", "Victim Mentality", "Trapped", "Limiting Beliefs"],
         ["Freedom", "New Perspective", "Empowerment", "Taking Control"],
         "Feeling trapped in relational patterns, self-imposed helplessness", "Realizing exit is open, breaking mental chains",
         "Paralyzed by corporate fear, imposter syndrome, career trap", "Asserting autonomy, seeking external solution",
         "Confronting mental cages created by rigid belief systems", "Remaining in victimhood out of secondary gain",
         "Constructing imaginary prison bars out of unexamined beliefs"),
        ("Nine", "09_nine", "Nine of Swords", "宝剑九", "Mars in Gemini (10°-20° / Despair and Cruelty)", "Yesod in Yetzirah",
         ["Anxiety", "Nightmares", "Insomnia", "Guilt", "Mental Anguish"],
         ["Hope", "Reaching Out", "Recovery", "Perspective"],
         "Paralyzing nighttime worry, relationship anxiety, guilt", "Realizing fears are exaggerated, opening up to partner",
         "Deadline panic, sleepless nights over audits, high stress", "Managing crisis calmly, seeking professional help",
         "Night terror of the shadow self during spiritual awakening", "Drowning in catastrophizing mental loops",
         "Tormenting oneself with imaginary worst-case scenarios"),
        ("Ten", "10_ten", "Ten of Swords", "宝剑十", "Sun in Gemini (20°-30° / Ruin)", "Malkuth in Yetzirah",
         ["Rock Bottom", "Painful Ending", "Inevitable Conclusion", "Dawn Approaches"],
         ["Recovery", "Resurrection", "Relief", "Learning Lessons"],
         "Final end of toxic relationship, rock bottom hit, dawn ahead", "Picking up pieces, healing, new dawn starting",
         "Project termination, company liquidation, utter reset", "Surviving collapse, pivot, rebuilding better foundation",
         "Total death of mental ego structures, bottom reached", "Prolonging agony by refusing to admit conclusion",
         "Dramatizing rock-bottom to avoid taking first step toward dawn"),
        ("Page", "11_page", "Page of Swords", "宝剑侍从", "Earth of Air / Princess of Rushing Winds", "Malkuth in Yetzirah",
         ["Curiosity", "Mental Agility", "Vigilance", "Inquisitive", "Truth-Seeking"],
         ["Gossip", "Deception", "All Talk", "Defensiveness"],
         "Intellectual banter, probing questions, curious flirting", "Snooping partner's phone, defensive paranoia",
         "Junior investigative researcher, sharp QA auditing, alert mind", "Nitpicking, spreading workplace rumors",
         "Alert spiritual inquiry, questioning dogmas with keen intellect", "Cynical intellectual sparring lacking heart",
         "Collecting intellectual data while resisting real transformation"),
        ("Knight", "12_knight", "Knight of Swords", "宝剑骑士", "Fire of Air / Lord of Wind and Breezes", "Tiphareth in Yetzirah",
         ["Ambition", "Direct Action", "Fast Thinking", "Drive", "Assertiveness"],
         ["Aggression", "Bluntness", "Recklessness", "Tactlessness"],
         "Blunt direct communication, fast-paced courtship, intense debate", "Tactless cruelty, bulldozing partner's feelings",
         "Aggressive market entry, swift bug triage, rapid execution", "Rushing without foresight, creating team conflict",
         "Intellectual warrior fighting for truth and mental freedom", "Fanatical ideological crusade destroying peace",
         "Charging headlong into verbal battles to defend intellectual pride"),
        ("Queen", "13_queen", "Queen of Swords", "宝剑王后", "Water of Air / Queen of Thrones of Air", "Briah in Yetzirah",
         ["Sharp Wit", "Clear Boundaries", "Independence", "Objective Truth"],
         ["Coldness", "Bitterness", "Cruel Judgment", "Cynicism"],
         "Clear relational boundaries, perceptive honesty, independence", "Cold emotional wall, cynical sharpness",
         "Objective executive oversight, rigorous code review, fair judge", "Harsh critique, unapproachable atmosphere",
         "Mastery of clear mental discernment and detached insight", "Using cynicism as armor against vulnerability",
         "Freezing out intimacy with razor-sharp intellectual judgment"),
        ("King", "14_king", "King of Swords", "宝剑国王", "Air of Air / Prince of Chariot of Winds", "Chokmah in Yetzirah",
         ["Mental Authority", "Intellectual Rigor", "Truth", "Discipline", "Strategy"],
         ["Tyranny", "Manipulation", "Cold Rationalism", "Dogmatism"],
         "Intellectually stimulating partner, ethical clear expectations", "Cold emotional tyrant, hyper-rational dismissal",
         "Chief Technology Officer, legal counsel, strategic architect", "Rigid bureaucracy, dismissing human factor",
         "Philosophical mastery, absolute alignment with universal truth", "Spiritual intellectualism divorced from compassion",
         "Sacrificing human compassion on the altar of abstract logic"),
    ]),

    # Pentacles (Earth)
    ("Pentacles", "pentacles", "Earth", [
        ("Ace", "01_ace", "Ace of Pentacles", "星币一", "Root of the Powers of Earth", "Kether in Assiah",
         ["Abundance", "Financial Opportunity", "New Venture", "Manifestation"],
         ["Missed Opportunity", "Financial Insecurity", "Poor Planning"],
         "Grounded loving bond, mutual financial stability, physical safety", "Financial anxiety straining relationship",
         "Seed funding, lucrative contract, tangible asset acquisition", "Missed business chance, poor budgeting",
         "Manifesting spiritual energy into tangible earthly service", "Material obsession blocking spiritual flow",
         "Clinging to gold while blind to intrinsic wealth of spirit"),
        ("Two", "02_two", "Two of Pentacles", "星币二", "Jupiter in Capricorn (0°-10° / Harmonious Change)", "Chokmah in Assiah",
         ["Balance", "Adaptability", "Time Management", "Prioritization", "Agility"],
         ["Overextended", "Financial Chaos", "Disorganization", "Dropping Balls"],
         "Juggling busy lives, balancing work and romance with humor", "Neglecting partner due to chaotic schedule",
         "Cash flow management, balancing multiple projects, agility", "Overextended commitments, budget deficit",
         "Flowing gracefully through dualities of material life", "Spiritual dissipation caused by material chaos",
         "Juggling superficial tasks to evade core existential decisions"),
        ("Three", "03_three", "Three of Pentacles", "星币三", "Mars in Capricorn (10°-20° / Material Works)", "Binah in Assiah",
         ["Mastery", "Collaboration", "Teamwork", "Skill", "Craftsmanship"],
         ["Lack of Teamwork", "Disorganized Effort", "Poor Craftsmanship"],
         "Building shared life together, working as dedicated team", "Friction over division of household labor",
         "Expert cross-functional engineering, design system mastery", "Siloed communication, inferior workmanship",
         "Building the temple of the soul through collective craftsmanship", "Spiritual pride in technique lacking heart",
         "Valuing technical perfectionism over human connection"),
        ("Four", "04_four", "Four of Pentacles", "星币四", "Sun in Capricorn (20°-30° / Earthly Power)", "Chesed in Assiah",
         ["Financial Security", "Conservatism", "Frugality", "Boundaries"],
         ["Greed", "Materialism", "Possessiveness", "Scarcity Mindset"],
         "Protective relationship, deep stability, solid shared assets", "Jealous possessiveness, control issues",
         "Capital preservation, tight budget, protecting core assets", "Stifling innovation through penny-pinching",
         "Grounding spiritual light into stable earthly vessel", "Clinging to spiritual dogmas out of fear of loss",
         "Hoarding resources out of chronic scarcity trauma"),
        ("Five", "05_five", "Five of Pentacles", "星币五", "Mercury in Taurus (0°-10° / Material Trouble)", "Geburah in Assiah",
         ["Hardship", "Financial Loss", "Isolation", "Feeling Left in Cold"],
         ["Recovery", "Spiritual Sanctuary", "Community Aid", "Turnaround"],
         "Weathering hard times together, emotional loneliness", "Recognizing support, healing relationship hardship",
         "Cash flow crunch, layoff, organizational crisis", "Emerging from crisis, finding bridge financing",
         "The dark night of material distress revealing true inner sanctuary", "Refusing to see open sanctuary door nearby",
         "Fixating on poverty mindset while sanctuary is within reach"),
        ("Six", "06_six", "Six of Pentacles", "星币六", "Moon in Taurus (10°-20° / Material Success)", "Tiphareth in Assiah",
         ["Generosity", "Charity", "Balanced Giving", "Mutual Support"],
         ["One-Sided Debt", "Strings Attached", "Power Imbalance"],
         "Equal emotional give-and-take, generous affection, mutual care", "Financial power imbalance, conditional giving",
         "Fair compensation, venture grant, mentorship, shared equity", "Exploitative contracts, unpaid overtime",
         "Universal circulation of energy and generous spiritual sharing", "Spiritual patronizing with strings attached",
         "Using charity to buy dominance and indebtedness"),
        ("Seven", "07_seven", "Seven of Pentacles", "星币七", "Saturn in Taurus (20°-30° / Success Unfulfilled)", "Netzach in Assiah",
         ["Patience", "Long-Term View", "Evaluation", "Sustainable Growth"],
         ["Impatience", "Wasted Effort", "Lack of Long-Term Vision"],
         "Patient cultivation of love, evaluating relationship trajectory", "Impatience with slow progress, frustration",
         "Reviewing quarterly ROI, waiting for harvest, sustainable code", "Sunk cost fallacy, failing to prune bad code",
         "Trusting the organic seasons of spiritual ripening", "Impatience demanding immediate spiritual fruit",
         "Anxiously watching seeds rather than tending soil with trust"),
        ("Eight", "08_eight", "Eight of Pentacles", "星币八", "Sun in Virgo (0°-10° / Prudence)", "Hod in Assiah",
         ["Craftsmanship", "Apprenticeship", "Dedication", "Detail-Oriented"],
         ["Perfectionism", "Monotony", "Lack of Ambition", "Rush Job"],
         "Daily devoted acts of love, steady reliable emotional growth", "Getting lost in routine, taking love as mechanical chore",
         "Mastering software craftsmanship, disciplined refactoring", "Careless rush jobs or paralyzing perfectionism",
         "Disciplined daily spiritual practice and repetitive inner work", "Mechanical ritual observance without inner devotion",
         "Hiding in minutiae to avoid confronting broader life vision"),
        ("Nine", "09_nine", "Nine of Pentacles", "星币九", "Venus in Virgo (10°-20° / Material Gain)", "Yesod in Assiah",
         ["Self-Reliance", "Refinement", "Abundance", "Grace", "Independence"],
         ["Over-Materialism", "Pretense", "Financial Dependency"],
         "Self-sufficient happy partner, refined elegant companionship", "Fear of sacrificing luxury for true intimacy",
         "High-earning specialist, autonomous consulting, financial summit", "Overspending on luxury, facade of success",
         "Living in harmony with earthly abundance and soul refinement", "Spiritual snobbery and solitary isolation",
         "Building gilded cage of self-sufficiency fearing messy intimacy"),
        ("Ten", "10_ten", "Ten of Pentacles", "星币十", "Mercury in Virgo (20°-30° / Wealth)", "Malkuth in Assiah",
         ["Legacy", "Generational Wealth", "Long-Term Security", "Tradition"],
         ["Family Dispute", "Financial Collapse", "Tradition Burden"],
         "Solid family dynasty, long-term multi-generational stability", "Family inheritance dispute, rigid family pressure",
         "Established enduring enterprise, thriving IPO, solid legacy", "Corporate restructuring, legacy code collapse",
         "Holistic realization of spirit grounded in ancestral continuum", "Being trapped by rigid family traditions",
         "Sacrificing present authentic joy to build dead monuments"),
        ("Page", "11_page", "Page of Pentacles", "星币侍从", "Earth of Earth / Princess of Echoing Hills", "Malkuth in Assiah",
         ["Study", "Ambition", "Grounded Start", "Practical Loyalty", "Apprentice"],
         ["Lack of Progress", "Procrastination", "Short-Term Focus"],
         "Reliable grounded partner, steady loyal dating, shared goals", "Boring or slow progress, procrastination",
         "Junior engineer eager to learn, solid prototype, diligent study", "Lack of practical follow-through, daydreaming",
         "Grounding new spiritual knowledge into physical habits", "Theoretical spiritual study without earthly action",
         "Collecting certificates and books without applying wisdom in life"),
        ("Knight", "12_knight", "Knight of Pentacles", "星币骑士", "Fire of Earth / Lord of Wide and Fertile Land", "Tiphareth in Assiah",
         ["Efficiency", "Routine", "Conservatism", "Methodical", "Reliability"],
         ["Stubbornness", "Workaholic", "Monotony", "Laziness"],
         "Ultra-reliable devoted partner, steady predictable care", "Stubborn inflexibility, romantic dullness",
         "Rock-solid project manager, reliable delivery, zero debt", "Resisting necessary pivots, obsessive workaholism",
         "Steadfast perseverance on the long spiritual path", "Spiritual dry spell and stubborn dogma",
         "Grinding through life on autopilot mistaking endurance for vitality"),
        ("Queen", "13_queen", "Queen of Pentacles", "星币王后", "Water of Earth / Queen of Thrones of Earth", "Briah in Assiah",
         ["Nurturing", "Practical Care", "Resourcefulness", "Warm Hospitality"],
         ["Smothering", "Financial Anxiety", "Work-Life Imbalance"],
         "Warm nurturing home, grounded secure love, practical care", "Overbearing material control, smothering care",
         "Operations executive, excellent resource stewardship, calm lead", "Financial anxiety, micromanaging budgets",
         "Embodiment of Gaia and mother earth wisdom", "Neglecting spirit in favor of excessive physical comfort",
         "Equating love with material provision and physical control"),
        ("King", "14_king", "King of Pentacles", "星币国王", "Air of Earth / Prince of Chariot of Earth", "Chokmah in Assiah",
         ["Enterprise", "Abundance", "Financial Leadership", "Security", "Stability"],
         ["Greed", "Materialism", "Stubbornness", "Indulgence"],
         "Generous solid provider, dependable pillar of strength", "Materialistic partner, measuring love by money",
         "Seasoned CEO, financial tycoon, sustainable enterprise builder", "Corporate greed, resisting market innovation",
         "Mastery over physical world and stewardship of universal wealth", "Materialistic blindness to spiritual values",
         "Valuing balance sheets over soul vitality"),
    ]),
]

def generate_rust_code():
    out = []
    out.append("""use serde::{Deserialize, Serialize};
use std::sync::LazyLock;
use crate::error::{TarotError, TarotResult};
use crate::facets::CardFacets;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum ArcanaType {
    Major,
    Minor,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum Suit {
    Wands,
    Cups,
    Swords,
    Pentacles,
}

impl Suit {
    pub fn element(&self) -> Element {
        match self {
            Suit::Wands => Element::Fire,
            Suit::Cups => Element::Water,
            Suit::Swords => Element::Air,
            Suit::Pentacles => Element::Earth,
        }
    }

    pub fn name_en(&self) -> &'static str {
        match self {
            Suit::Wands => "Wands",
            Suit::Cups => "Cups",
            Suit::Swords => "Swords",
            Suit::Pentacles => "Pentacles",
        }
    }

    pub fn name_zh(&self) -> &'static str {
        match self {
            Suit::Wands => "权杖",
            Suit::Cups => "圣杯",
            Suit::Swords => "宝剑",
            Suit::Pentacles => "星币",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum Rank {
    Ace = 1,
    Two = 2,
    Three = 3,
    Four = 4,
    Five = 5,
    Six = 6,
    Seven = 7,
    Eight = 8,
    Nine = 9,
    Ten = 10,
    Page = 11,
    Knight = 12,
    Queen = 13,
    King = 14,
}

impl Rank {
    pub fn name_en(&self) -> &'static str {
        match self {
            Rank::Ace => "Ace",
            Rank::Two => "Two",
            Rank::Three => "Three",
            Rank::Four => "Four",
            Rank::Five => "Five",
            Rank::Six => "Six",
            Rank::Seven => "Seven",
            Rank::Eight => "Eight",
            Rank::Nine => "Nine",
            Rank::Ten => "Ten",
            Rank::Page => "Page",
            Rank::Knight => "Knight",
            Rank::Queen => "Queen",
            Rank::King => "King",
        }
    }

    pub fn name_zh(&self) -> &'static str {
        match self {
            Rank::Ace => "首牌 (一)",
            Rank::Two => "二",
            Rank::Three => "三",
            Rank::Four => "四",
            Rank::Five => "五",
            Rank::Six => "六",
            Rank::Seven => "七",
            Rank::Eight => "八",
            Rank::Nine => "九",
            Rank::Ten => "十",
            Rank::Page => "侍从",
            Rank::Knight => "骑士",
            Rank::Queen => "王后",
            Rank::King => "国王",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum Element {
    Fire,
    Water,
    Air,
    Earth,
    Spirit,
    None,
}

impl Element {
    pub fn name_zh(&self) -> &'static str {
        match self {
            Element::Fire => "火",
            Element::Water => "水",
            Element::Air => "风",
            Element::Earth => "土",
            Element::Spirit => "灵",
            Element::None => "无",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum Orientation {
    Upright = 0,
    Reversed = 1,
}

impl Orientation {
    pub fn is_upright(&self) -> bool {
        matches!(self, Orientation::Upright)
    }

    pub fn is_reversed(&self) -> bool {
        matches!(self, Orientation::Reversed)
    }

    pub fn name_zh(&self) -> &'static str {
        match self {
            Orientation::Upright => "正位",
            Orientation::Reversed => "逆位",
        }
    }

    pub fn name_en(&self) -> &'static str {
        match self {
            Orientation::Upright => "Upright",
            Orientation::Reversed => "Reversed",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct StaticCardFacets {
    pub general_upright: &'static [&'static str],
    pub general_reversed: &'static [&'static str],
    pub love_upright: &'static str,
    pub love_reversed: &'static str,
    pub career_upright: &'static str,
    pub career_reversed: &'static str,
    pub spiritual_upright: &'static str,
    pub spiritual_reversed: &'static str,
    pub shadow_aspect: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct StaticCardDefinition {
    pub id: u8,
    pub key: &'static str,
    pub arcana: ArcanaType,
    pub suit: Option<Suit>,
    pub rank: Option<Rank>,
    pub element: Element,
    pub name_en: &'static str,
    pub name_zh: &'static str,
    pub astrology: Option<&'static str>,
    pub hebrew_letter: Option<&'static str>,
    pub facets: StaticCardFacets,
}

impl StaticCardDefinition {
    pub fn to_owned_card(&self) -> Card {
        Card {
            id: self.id,
            key: self.key.to_string(),
            arcana: self.arcana,
            suit: self.suit,
            rank: self.rank,
            element: self.element,
            name_en: self.name_en.to_string(),
            name_zh: self.name_zh.to_string(),
            astrology: self.astrology.map(|s| s.to_string()),
            hebrew_letter: self.hebrew_letter.map(|s| s.to_string()),
            facets: CardFacets::new(
                self.facets.general_upright,
                self.facets.general_reversed,
                self.facets.love_upright,
                self.facets.love_reversed,
                self.facets.career_upright,
                self.facets.career_reversed,
                self.facets.spiritual_upright,
                self.facets.spiritual_reversed,
                self.facets.shadow_aspect,
            ),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, uniffi::Record)]
pub struct Card {
    pub id: u8,
    pub key: String,
    pub arcana: ArcanaType,
    pub suit: Option<Suit>,
    pub rank: Option<Rank>,
    pub element: Element,
    pub name_en: String,
    pub name_zh: String,
    pub astrology: Option<String>,
    pub hebrew_letter: Option<String>,
    pub facets: CardFacets,
}

/// 78-Card Static Registry in .rodata (Zero Dynamic Heap Allocation)
pub static ALL_CARDS: [StaticCardDefinition; 78] = [
""")

    # 22 Major
    for card in MAJOR_CARDS:
        cid, key, elem, name_en, name_zh, astro, hebrew, gu, gr, lu, lr, cu, cr, su, sr, shadow = card
        gu_str = ", ".join(f'"{x}"' for x in gu)
        gr_str = ", ".join(f'"{x}"' for x in gr)
        out.append(f"""    StaticCardDefinition {{
        id: {cid},
        key: "{key}",
        arcana: ArcanaType::Major,
        suit: None,
        rank: None,
        element: Element::{elem},
        name_en: "{name_en}",
        name_zh: "{name_zh}",
        astrology: Some("{astro}"),
        hebrew_letter: Some("{hebrew}"),
        facets: StaticCardFacets {{
            general_upright: &[{gu_str}],
            general_reversed: &[{gr_str}],
            love_upright: "{lu}",
            love_reversed: "{lr}",
            career_upright: "{cu}",
            career_reversed: "{cr}",
            spiritual_upright: "{su}",
            spiritual_reversed: "{sr}",
            shadow_aspect: "{shadow}",
        }},
    }},""")

    # 56 Minor
    cid_counter = 22
    for suit_enum, suit_key, suit_elem, ranks in MINOR_DATA:
        for rank_enum, rank_key, name_en, name_zh, astro, hebrew, gu, gr, lu, lr, cu, cr, su, sr, shadow in ranks:
            gu_str = ", ".join(f'"{x}"' for x in gu)
            gr_str = ", ".join(f'"{x}"' for x in gr)
            out.append(f"""    StaticCardDefinition {{
        id: {cid_counter},
        key: "minor_{suit_key}_{rank_key}",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::{suit_enum}),
        rank: Some(Rank::{rank_enum}),
        element: Element::{suit_elem},
        name_en: "{name_en}",
        name_zh: "{name_zh}",
        astrology: Some("{astro}"),
        hebrew_letter: Some("{hebrew}"),
        facets: StaticCardFacets {{
            general_upright: &[{gu_str}],
            general_reversed: &[{gr_str}],
            love_upright: "{lu}",
            love_reversed: "{lr}",
            career_upright: "{cu}",
            career_reversed: "{cr}",
            spiritual_upright: "{su}",
            spiritual_reversed: "{sr}",
            shadow_aspect: "{shadow}",
        }},
    }},""")
            cid_counter += 1

    out.append("""
];

static RUNTIME_CARDS_CACHE: LazyLock<Vec<Card>> = LazyLock::new(|| {
    ALL_CARDS.iter().map(|c| c.to_owned_card()).collect()
});

pub struct CardDeck;

impl CardDeck {
    /// Zero-allocation, O(1) static reference retrieval (< 1ns)
    #[inline(always)]
    pub fn get_static(id: u8) -> TarotResult<&'static StaticCardDefinition> {
        if id >= 78 {
            return Err(TarotError::CardIndexOutOfBounds(id));
        }
        Ok(&ALL_CARDS[id as usize])
    }

    /// Retrieves an owned Card clone from the LazyLock static cache
    pub fn get_by_id(id: u8) -> TarotResult<Card> {
        if id >= 78 {
            return Err(TarotError::CardIndexOutOfBounds(id));
        }
        Ok(RUNTIME_CARDS_CACHE[id as usize].clone())
    }

    /// Returns standard 78 cards from LazyLock cache
    pub fn standard_78() -> Vec<Card> {
        RUNTIME_CARDS_CACHE.clone()
    }
}
""")
    return "\n".join(out)

if __name__ == "__main__":
    code = generate_rust_code()
    with open("crates/taroturn-core/src/card.rs", "w", encoding="utf-8") as f:
        f.write(code)
    print("Successfully generated crates/taroturn-core/src/card.rs with 78 static cards!")
