use serde::{Deserialize, Serialize};
use crate::error::{TarotError, TarotResult};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum SlotConstraint {
    Any,
    MajorOnly,
    MinorOnly,
    WandsOnly,
    CupsOnly,
    SwordsOnly,
    PentaclesOnly,
    CourtOnly,
    PipOnly,
}

impl SlotConstraint {
    pub fn matches(&self, card: &crate::card::Card) -> bool {
        use crate::card::{ArcanaType, Rank, Suit};
        match self {
            SlotConstraint::Any => true,
            SlotConstraint::MajorOnly => card.arcana == ArcanaType::Major,
            SlotConstraint::MinorOnly => card.arcana == ArcanaType::Minor,
            SlotConstraint::WandsOnly => card.suit == Some(Suit::Wands),
            SlotConstraint::CupsOnly => card.suit == Some(Suit::Cups),
            SlotConstraint::SwordsOnly => card.suit == Some(Suit::Swords),
            SlotConstraint::PentaclesOnly => card.suit == Some(Suit::Pentacles),
            SlotConstraint::CourtOnly => {
                card.arcana == ArcanaType::Minor
                    && matches!(card.rank, Some(Rank::Page | Rank::Knight | Rank::Queen | Rank::King))
            }
            SlotConstraint::PipOnly => {
                card.arcana == ArcanaType::Minor
                    && !matches!(card.rank, Some(Rank::Page | Rank::Knight | Rank::Queen | Rank::King))
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum SlotRelationType {
    Crosses,
    FlowsTo,
    Supports,
    Illuminates,
    Opposes,
    Synthesizes,
    Reflects,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SlotEdge {
    pub source_slot_id: u8,
    pub target_slot_id: u8,
    pub relation: SlotRelationType,
    pub weight: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct SpreadSlot {
    pub slot_id: u8,
    pub title_en: String,
    pub title_zh: String,
    pub meaning_prompt: String,
    pub x: f32,
    pub y: f32,
    pub rotation_deg: f32,
    pub z_index: i16,
    pub constraint: SlotConstraint,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, uniffi::Enum)]
pub enum SpreadCategory {
    Daily,
    Decision,
    Relationship,
    Comprehensive,
    Custom,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, uniffi::Record)]
pub struct Spread {
    pub id: String,
    pub name_en: String,
    pub name_zh: String,
    pub description: String,
    pub category: SpreadCategory,
    pub slots: Vec<SpreadSlot>,
    pub edges: Vec<SlotEdge>,
}

impl Spread {
    pub fn slot_count(&self) -> usize {
        self.slots.len()
    }

    pub fn canonical_spreads() -> Vec<Spread> {
        vec![
            Spread {
                id: "daily_single".into(),
                name_en: "Daily Focus / Oracle".into(),
                name_zh: "每日启示 / 单张牌".into(),
                description: "Single card draw for daily contemplation or focused guidance.".into(),
                category: SpreadCategory::Daily,
                slots: vec![SpreadSlot {
                    slot_id: 0,
                    title_en: "Core Oracle".into(),
                    title_zh: "核心启示".into(),
                    meaning_prompt: "The primary energy and guidance for this moment.".into(),
                    x: 0.5,
                    y: 0.5,
                    rotation_deg: 0.0,
                    z_index: 0,
                    constraint: SlotConstraint::Any,
                }],
                edges: vec![],
            },
            Spread {
                id: "three_cards_time".into(),
                name_en: "Past, Present, Future (Time Stream)".into(),
                name_zh: "时间之流 (过去-现在-未来)".into(),
                description: "Temporal evolution of circumstances and energetic momentum.".into(),
                category: SpreadCategory::Comprehensive,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Past Influence".into(),
                        title_zh: "过去根基".into(),
                        meaning_prompt: "Root cause and foundational context leading up to now.".into(),
                        x: 0.2,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Present Reality".into(),
                        title_zh: "现在处境".into(),
                        meaning_prompt: "Current energetic climate and focal challenge.".into(),
                        x: 0.5,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Future Outcome".into(),
                        title_zh: "未来走向".into(),
                        meaning_prompt: "Natural trajectory if present course remains unchanged.".into(),
                        x: 0.8,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 2,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                ],
            },
            Spread {
                id: "holy_triangle".into(),
                name_en: "Situation, Obstacle, Advice (Holy Triangle)".into(),
                name_zh: "圣三角 (现状-障碍-建议)".into(),
                description: "Action-oriented decision analysis and obstacle diagnosis.".into(),
                category: SpreadCategory::Decision,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Situation".into(),
                        title_zh: "现状全貌".into(),
                        meaning_prompt: "The underlying reality of the matter.".into(),
                        x: 0.3,
                        y: 0.7,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Obstacle".into(),
                        title_zh: "核心阻碍".into(),
                        meaning_prompt: "Hidden friction or explicit challenge facing you.".into(),
                        x: 0.7,
                        y: 0.7,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Advice".into(),
                        title_zh: "指引建议".into(),
                        meaning_prompt: "Optimal attitude and decisive action recommended.".into(),
                        x: 0.5,
                        y: 0.3,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::Opposes,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 2,
                        relation: SlotRelationType::Synthesizes,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 2,
                        relation: SlotRelationType::Synthesizes,
                        weight: 1.0,
                    },
                ],
            },
            Spread {
                id: "four_elements".into(),
                name_en: "Four Elements Balance".into(),
                name_zh: "四要素平衡牌阵".into(),
                description: "Evaluating balance across Action, Emotion, Intellect, and Materiality.".into(),
                category: SpreadCategory::Comprehensive,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Fire (Will / Action)".into(),
                        title_zh: "火之位 (意志与行动)".into(),
                        meaning_prompt: "Your passion, momentum, and creative drive.".into(),
                        x: 0.5,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Water (Emotions / Relationships)".into(),
                        title_zh: "水之位 (情感与直觉)".into(),
                        meaning_prompt: "Your subconscious desires and emotional bonds.".into(),
                        x: 0.8,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Air (Intellect / Communication)".into(),
                        title_zh: "风之位 (心智与沟通)".into(),
                        meaning_prompt: "Your mental clarity, thoughts, and strategy.".into(),
                        x: 0.2,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 3,
                        title_en: "Earth (Material / Body)".into(),
                        title_zh: "土之位 (物质与躯体)".into(),
                        meaning_prompt: "Your financial stability and physical health.".into(),
                        x: 0.5,
                        y: 0.8,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 2,
                        relation: SlotRelationType::Illuminates,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 3,
                        relation: SlotRelationType::Supports,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::Opposes,
                        weight: 0.8,
                    },
                    SlotEdge {
                        source_slot_id: 2,
                        target_slot_id: 3,
                        relation: SlotRelationType::Opposes,
                        weight: 0.8,
                    },
                ],
            },
            Spread {
                id: "two_choices".into(),
                name_en: "Two Choices / Crossroads Spread".into(),
                name_zh: "二选一抉择牌阵".into(),
                description: "Comparing comparative trajectories of Choice A vs Choice B.".into(),
                category: SpreadCategory::Decision,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Current State".into(),
                        title_zh: "抉择原点".into(),
                        meaning_prompt: "The nexus and dilemma facing you today.".into(),
                        x: 0.5,
                        y: 0.8,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Choice A Process".into(),
                        title_zh: "选项 A 发展历程".into(),
                        meaning_prompt: "The experiences and effort required in Option A.".into(),
                        x: 0.3,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Choice A Result".into(),
                        title_zh: "选项 A 最终结果".into(),
                        meaning_prompt: "The eventual harvest and outcome of Option A.".into(),
                        x: 0.3,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 3,
                        title_en: "Choice B Process".into(),
                        title_zh: "选项 B 发展历程".into(),
                        meaning_prompt: "The experiences and effort required in Option B.".into(),
                        x: 0.7,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 4,
                        title_en: "Choice B Result".into(),
                        title_zh: "选项 B 最终结果".into(),
                        meaning_prompt: "The eventual harvest and outcome of Option B.".into(),
                        x: 0.7,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 2,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 3,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 3,
                        target_slot_id: 4,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 2,
                        target_slot_id: 4,
                        relation: SlotRelationType::Opposes,
                        weight: 1.0,
                    },
                ],
            },
            Spread {
                id: "hexagram_7".into(),
                name_en: "Hexagram / Star of David Spread".into(),
                name_zh: "六芒星 / 大卫星牌阵".into(),
                description: "Deep holistic inquiry integrating internal motives and external forces.".into(),
                category: SpreadCategory::Comprehensive,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Past".into(),
                        title_zh: "过去原因".into(),
                        meaning_prompt: "Past circumstances that established this situation.".into(),
                        x: 0.5,
                        y: 0.15,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Present".into(),
                        title_zh: "现在状况".into(),
                        meaning_prompt: "Current focal dynamics.".into(),
                        x: 0.8,
                        y: 0.65,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Future".into(),
                        title_zh: "未来趋势".into(),
                        meaning_prompt: "Future developmental arc.".into(),
                        x: 0.2,
                        y: 0.65,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 3,
                        title_en: "Solution".into(),
                        title_zh: "应对方法".into(),
                        meaning_prompt: "Effective strategies to unlock progress.".into(),
                        x: 0.5,
                        y: 0.85,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 4,
                        title_en: "Surroundings".into(),
                        title_zh: "周围环境".into(),
                        meaning_prompt: "Attitudes and energies of people around you.".into(),
                        x: 0.2,
                        y: 0.35,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 5,
                        title_en: "Hopes and Fears".into(),
                        title_zh: "愿望与恐惧".into(),
                        meaning_prompt: "Subconscious aspirations and hidden anxieties.".into(),
                        x: 0.8,
                        y: 0.35,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 6,
                        title_en: "Outcome / Synthesis".into(),
                        title_zh: "核心结论".into(),
                        meaning_prompt: "Final holistic culmination.".into(),
                        x: 0.5,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 1,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 2,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 3,
                        target_slot_id: 6,
                        relation: SlotRelationType::Synthesizes,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 4,
                        target_slot_id: 5,
                        relation: SlotRelationType::Reflects,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 6,
                        relation: SlotRelationType::Supports,
                        weight: 1.0,
                    },
                ],
            },
            Spread {
                id: "horseshoe_7".into(),
                name_en: "Horseshoe Spread".into(),
                name_zh: "马蹄铁拱形牌阵".into(),
                description: "Sequential 7-card arc illustrating past, present, subconscious, obstacles, environment, advice, and outcome.".into(),
                category: SpreadCategory::Comprehensive,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "Past Influences".into(),
                        title_zh: "过去根源".into(),
                        meaning_prompt: "Historical events and roots leading up to now.".into(),
                        x: 0.15,
                        y: 0.7,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "Present Situation".into(),
                        title_zh: "现在处境".into(),
                        meaning_prompt: "Current realities and feelings.".into(),
                        x: 0.25,
                        y: 0.45,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "Subconscious Doubts".into(),
                        title_zh: "潜意识疑虑".into(),
                        meaning_prompt: "Hidden thoughts and subconscious factors.".into(),
                        x: 0.4,
                        y: 0.25,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 3,
                        title_en: "Obstacles / Roadblocks".into(),
                        title_zh: "核心阻碍".into(),
                        meaning_prompt: "Unseen friction or direct challenges.".into(),
                        x: 0.5,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 4,
                        title_en: "External Environment".into(),
                        title_zh: "外部环境".into(),
                        meaning_prompt: "Energies and opinions of others around you.".into(),
                        x: 0.6,
                        y: 0.25,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 5,
                        title_en: "Best Course of Action".into(),
                        title_zh: "应对指引".into(),
                        meaning_prompt: "Decisive action and constructive guidance.".into(),
                        x: 0.75,
                        y: 0.45,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 6,
                        title_en: "Final Outcome".into(),
                        title_zh: "最终结局".into(),
                        meaning_prompt: "Ultimate natural resolution.".into(),
                        x: 0.85,
                        y: 0.7,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 1,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 2,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 2,
                        target_slot_id: 3,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 3,
                        target_slot_id: 4,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 4,
                        target_slot_id: 5,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 5,
                        target_slot_id: 6,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                ],
            },
            Spread {
                id: "celtic_cross".into(),
                name_en: "Celtic Cross".into(),
                name_zh: "凯尔特十字牌阵".into(),
                description: "The quintessential 10-card profound reading revealing conscious, subconscious, past, future, and outcome.".into(),
                category: SpreadCategory::Comprehensive,
                slots: vec![
                    SpreadSlot {
                        slot_id: 0,
                        title_en: "The Heart / Present".into(),
                        title_zh: "现状核心".into(),
                        meaning_prompt: "The primary theme and central situation right now.".into(),
                        x: 0.35,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 1,
                        title_en: "The Crossing / Obstacle".into(),
                        title_zh: "交叉阻碍".into(),
                        meaning_prompt: "The immediate obstacle or challenging dynamic crossing you.".into(),
                        x: 0.35,
                        y: 0.5,
                        rotation_deg: 90.0,
                        z_index: 1,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 2,
                        title_en: "The Root / Subconscious".into(),
                        title_zh: "潜意识根基".into(),
                        meaning_prompt: "Deep underlying subconscious motives and root origins.".into(),
                        x: 0.35,
                        y: 0.8,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 3,
                        title_en: "The Recent Past".into(),
                        title_zh: "过去影响".into(),
                        meaning_prompt: "Events and energies that just passed but still echo.".into(),
                        x: 0.15,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 4,
                        title_en: "The Crown / Conscious Goal".into(),
                        title_zh: "显意识期望".into(),
                        meaning_prompt: "What you consciously aspire to or best possible outcome.".into(),
                        x: 0.35,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 5,
                        title_en: "The Near Future".into(),
                        title_zh: "近期未来".into(),
                        meaning_prompt: "What approaches in the immediate upcoming weeks.".into(),
                        x: 0.55,
                        y: 0.5,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 6,
                        title_en: "Yourself / Attitude".into(),
                        title_zh: "自我心态".into(),
                        meaning_prompt: "Your internal stance, mindset, and self-perception.".into(),
                        x: 0.8,
                        y: 0.8,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 7,
                        title_en: "External Environment".into(),
                        title_zh: "外部环境".into(),
                        meaning_prompt: "Energetic impact of family, coworkers, and environment.".into(),
                        x: 0.8,
                        y: 0.6,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 8,
                        title_en: "Hopes & Fears".into(),
                        title_zh: "希望与忧虑".into(),
                        meaning_prompt: "Your deepest secret desires and underlying fears.".into(),
                        x: 0.8,
                        y: 0.4,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                    SpreadSlot {
                        slot_id: 9,
                        title_en: "Final Outcome".into(),
                        title_zh: "最终结果".into(),
                        meaning_prompt: "The ultimate long-term resolution and culmination.".into(),
                        x: 0.8,
                        y: 0.2,
                        rotation_deg: 0.0,
                        z_index: 0,
                        constraint: SlotConstraint::Any,
                    },
                ],
                edges: vec![
                    SlotEdge {
                        source_slot_id: 1,
                        target_slot_id: 0,
                        relation: SlotRelationType::Crosses,
                        weight: 1.2,
                    },
                    SlotEdge {
                        source_slot_id: 2,
                        target_slot_id: 0,
                        relation: SlotRelationType::Supports,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 3,
                        target_slot_id: 0,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 4,
                        target_slot_id: 0,
                        relation: SlotRelationType::Illuminates,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 0,
                        target_slot_id: 5,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 6,
                        target_slot_id: 7,
                        relation: SlotRelationType::Reflects,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 8,
                        target_slot_id: 9,
                        relation: SlotRelationType::Supports,
                        weight: 1.0,
                    },
                    SlotEdge {
                        source_slot_id: 5,
                        target_slot_id: 9,
                        relation: SlotRelationType::FlowsTo,
                        weight: 1.0,
                    },
                ],
            },
        ]
    }

    pub fn get_by_id(id: &str) -> TarotResult<Spread> {
        Self::canonical_spreads()
            .into_iter()
            .find(|s| s.id == id)
            .ok_or_else(|| TarotError::SpreadNotFound(id.to_string()))
    }
}
